//! Windows Service integration: the SCM control handler plus `install` /
//! `uninstall`.
//!
//! `talos-agent install` registers the service (auto-start, LocalSystem). The
//! Service Control Manager then launches `talos-agent service-run`, which
//! dispatches into [`run_as_service`], reports **RUNNING**, and runs the daemon
//! until the SCM sends **STOP** (which trips the shared stop flag so the IPC
//! loop and worker threads wind down cleanly).
//!
//! This module is Windows-only; everything below is validated by the Windows CI
//! job, which builds `talos-agent.exe` for `x86_64-pc-windows-msvc`.

use std::ffi::OsString;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::Duration;

use anyhow::{Context, Result};
use windows_service::service::{
    ServiceAccess, ServiceControl, ServiceControlAccept, ServiceErrorControl, ServiceExitCode,
    ServiceInfo, ServiceStartType, ServiceState, ServiceStatus, ServiceType,
};
use windows_service::service_control_handler::{self, ServiceControlHandlerResult};
use windows_service::service_manager::{ServiceManager, ServiceManagerAccess};
use windows_service::{define_windows_service, service_dispatcher};

const SERVICE_NAME: &str = "TalosAgent";
const SERVICE_DISPLAY: &str = "Talos EPP Agent";
const SERVICE_DESCRIPTION: &str = "Talos EPP endpoint protection agent — real-time on-access \
scanning with auto-quarantine, ransomware canary guard, and OS-firewall C2 blocking.";
const SERVICE_TYPE: ServiceType = ServiceType::OWN_PROCESS;

define_windows_service!(ffi_service_main, service_main);

/// Hand control to the SCM dispatcher (invoked by `talos-agent service-run`).
pub fn run_as_service() -> Result<()> {
    service_dispatcher::start(SERVICE_NAME, ffi_service_main)
        .context("starting the service dispatcher")?;
    Ok(())
}

/// SCM entry point generated by `define_windows_service!`.
fn service_main(_arguments: Vec<OsString>) {
    if let Err(e) = run_service() {
        eprintln!("talos-agent service error: {e:#}");
    }
}

fn run_service() -> Result<()> {
    let stop = Arc::new(AtomicBool::new(false));
    let stop_for_handler = Arc::clone(&stop);

    let event_handler = move |control_event| -> ServiceControlHandlerResult {
        match control_event {
            ServiceControl::Stop | ServiceControl::Shutdown => {
                stop_for_handler.store(true, Ordering::SeqCst);
                ServiceControlHandlerResult::NoError
            }
            ServiceControl::Interrogate => ServiceControlHandlerResult::NoError,
            _ => ServiceControlHandlerResult::NotImplemented,
        }
    };

    let status_handle = service_control_handler::register(SERVICE_NAME, event_handler)
        .context("registering the service control handler")?;

    status_handle
        .set_service_status(status(
            ServiceState::Running,
            ServiceControlAccept::STOP | ServiceControlAccept::SHUTDOWN,
            0,
        ))
        .context("reporting RUNNING")?;

    // Run the daemon until the SCM trips the stop flag.
    let result = crate::daemon::run(Arc::clone(&stop));

    let exit = u32::from(result.is_err());
    let _ = status_handle.set_service_status(status(
        ServiceState::Stopped,
        ServiceControlAccept::empty(),
        exit,
    ));
    result
}

fn status(state: ServiceState, accepted: ServiceControlAccept, exit: u32) -> ServiceStatus {
    ServiceStatus {
        service_type: SERVICE_TYPE,
        current_state: state,
        controls_accepted: accepted,
        exit_code: ServiceExitCode::Win32(exit),
        checkpoint: 0,
        wait_hint: Duration::default(),
        process_id: None,
    }
}

/// `talos-agent install` — register the service to auto-start under LocalSystem
/// and start it immediately.
pub fn install() -> Result<()> {
    let manager = ServiceManager::local_computer(
        None::<&str>,
        ServiceManagerAccess::CONNECT | ServiceManagerAccess::CREATE_SERVICE,
    )
    .context("opening the service manager (run as Administrator)")?;

    let exe = std::env::current_exe().context("locating the agent executable")?;
    let info = ServiceInfo {
        name: OsString::from(SERVICE_NAME),
        display_name: OsString::from(SERVICE_DISPLAY),
        service_type: SERVICE_TYPE,
        start_type: ServiceStartType::AutoStart,
        error_control: ServiceErrorControl::Normal,
        executable_path: exe,
        launch_arguments: vec![OsString::from("service-run")],
        dependencies: vec![],
        account_name: None, // LocalSystem
        account_password: None,
    };

    let service = manager
        .create_service(&info, ServiceAccess::CHANGE_CONFIG | ServiceAccess::START)
        .context("creating the service")?;
    let _ = service.set_description(SERVICE_DESCRIPTION);
    service.start::<&str>(&[]).context("starting the service")?;
    println!("installed and started '{SERVICE_NAME}' ({SERVICE_DISPLAY}).");
    Ok(())
}

/// `talos-agent uninstall` — stop (if running) and delete the service.
pub fn uninstall() -> Result<()> {
    let manager = ServiceManager::local_computer(None::<&str>, ServiceManagerAccess::CONNECT)
        .context("opening the service manager (run as Administrator)")?;
    let service = manager
        .open_service(
            SERVICE_NAME,
            ServiceAccess::QUERY_STATUS | ServiceAccess::STOP | ServiceAccess::DELETE,
        )
        .context("opening the service (is it installed?)")?;

    if let Ok(state) = service.query_status() {
        if state.current_state != ServiceState::Stopped {
            let _ = service.stop();
        }
    }
    service.delete().context("deleting the service")?;
    println!("removed service '{SERVICE_NAME}'.");
    Ok(())
}
