//! Talos EPP — desktop GUI (egui/eframe). A self-contained, dark "security
//! console" front-end over the same engine the CLI uses.
//!
//! The layout borrows the patterns that make the leading suites approachable:
//! a Bitdefender-style **Security Advisor** with contextual recommendations, a
//! Malwarebytes-style **Protection module grid**, an ESET/Kaspersky-style
//! grouped navigation, a persisted **Activity** log, and a power-user
//! **Settings** panel whose toggles genuinely change how scans run.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod config;
mod engine_glue;
mod history;

use std::path::PathBuf;
use std::sync::mpsc::{Receiver, TryRecvError};
use std::time::{SystemTime, UNIX_EPOCH};

use eframe::egui;
use egui::{Color32, RichText};
use scanner_core::{ScanReport, Severity};

use config::{Schedule, TalosConfig};
use engine_glue::ScanMsg;

// ---- palette -------------------------------------------------------------
const BG: Color32 = Color32::from_rgb(0x12, 0x16, 0x1d);
const PANEL: Color32 = Color32::from_rgb(0x18, 0x1d, 0x26);
const CARD: Color32 = Color32::from_rgb(0x1f, 0x26, 0x31);
const TEXT: Color32 = Color32::from_rgb(0xe6, 0xe9, 0xef);
const DIM: Color32 = Color32::from_rgb(0x93, 0x9f, 0xb0);
const ACCENT: Color32 = Color32::from_rgb(0xe1, 0x1d, 0x2a); // Talos red
const GREEN: Color32 = Color32::from_rgb(0x2b, 0xd6, 0x6a);
const AMBER: Color32 = Color32::from_rgb(0xff, 0xb0, 0x20);

fn main() -> eframe::Result<()> {
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_inner_size([1040.0, 700.0])
            .with_min_inner_size([880.0, 600.0])
            .with_icon(std::sync::Arc::new(load_icon()))
            .with_title("Talos EPP — Endpoint Protection"),
        ..Default::default()
    };
    eframe::run_native(
        "Talos EPP",
        options,
        Box::new(|cc| {
            install_theme(&cc.egui_ctx);
            Ok(Box::new(TalosApp::new()))
        }),
    )
}

/// The app icon for the window/taskbar, as raw 64x64 RGBA generated by
/// `tools/make_icon.py` (the same artwork embedded into the .exe).
fn load_icon() -> egui::IconData {
    egui::IconData {
        rgba: include_bytes!("../assets/icon-64.rgba").to_vec(),
        width: 64,
        height: 64,
    }
}

fn install_theme(ctx: &egui::Context) {
    let mut v = egui::Visuals::dark();
    v.panel_fill = PANEL;
    v.window_fill = PANEL;
    v.extreme_bg_color = BG;
    v.override_text_color = Some(TEXT);
    v.selection.bg_fill = ACCENT.linear_multiply(0.55);
    v.widgets.hovered.bg_fill = CARD;
    v.widgets.inactive.bg_fill = CARD;
    v.widgets.active.bg_fill = ACCENT;
    ctx.set_visuals(v);

    let mut style = (*ctx.style()).clone();
    style.spacing.item_spacing = egui::vec2(10.0, 10.0);
    style.spacing.button_padding = egui::vec2(12.0, 8.0);
    ctx.set_style(style);
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum View {
    Dashboard,
    Protection,
    Scan,
    Quarantine,
    Activity,
    Intel,
    Settings,
    About,
}

#[derive(Clone, Copy)]
struct Done {
    files: u64,
    malicious: u64,
    suspicious: u64,
    ms: u64,
    bytes: u64,
}

/// A one-click action the Security Advisor can recommend.
#[derive(Clone, Copy)]
enum Advice {
    QuickScan,
    Update,
    Quarantine,
    Review,
}

struct TalosApp {
    view: View,
    version: String,
    tenant: Option<String>,
    config: TalosConfig,
    hashes: usize,
    yara: usize,
    quarantined: usize,

    custom_path: String,
    new_exclusion: String,

    rx: Option<Receiver<ScanMsg>>,
    scanning: bool,
    scan_label: String,
    scanned: u64,
    current: String,
    threats: Vec<ScanReport>,
    last: Option<Done>,
    last_scan_unix: u64,
    status: String,
    sig_source: String,
    last_update_unix: u64,
    updating: bool,
    update_rx: Option<Receiver<scanner_core::UpdateReport>>,

    q_items: Vec<scanner_core::QuarantineEntry>,
    q_loaded: bool,

    activity: Vec<history::Event>,
    activity_loaded: bool,

    realtime: Option<engine_glue::RealtimeHandle>,
    realtime_paths: usize,
    realtime_hits: u64,

    intel_query: String,
    intel_source: String,
    intel_lines: Vec<String>,
    intel_busy: bool,
    intel_rx: Option<Receiver<Result<Vec<scanner_core::IntelReport>, String>>>,

    /// The Talos bronze-guardian emblem, lazily uploaded as a GPU texture.
    hero_tex: Option<egui::TextureHandle>,
}

impl TalosApp {
    fn new() -> Self {
        let (hashes, yara, quarantined) = engine_glue::inventory_counts();
        Self {
            view: View::Dashboard,
            version: env!("CARGO_PKG_VERSION").to_string(),
            tenant: std::env::var("TALOS_TENANT").ok().filter(|s| !s.is_empty()),
            config: TalosConfig::load(),
            hashes,
            yara,
            quarantined,
            custom_path: String::new(),
            new_exclusion: String::new(),
            rx: None,
            scanning: false,
            scan_label: String::new(),
            scanned: 0,
            current: String::new(),
            threats: Vec::new(),
            last: None,
            last_scan_unix: 0,
            status: "Ready.".to_string(),
            sig_source: engine_glue::signatures_source(),
            last_update_unix: 0,
            updating: false,
            update_rx: None,
            q_items: Vec::new(),
            q_loaded: false,
            activity: Vec::new(),
            activity_loaded: false,
            realtime: None,
            realtime_paths: 0,
            realtime_hits: 0,
            intel_query: String::new(),
            intel_source: String::new(),
            intel_lines: Vec::new(),
            intel_busy: false,
            intel_rx: None,
            hero_tex: None,
        }
    }

    fn start_realtime(&mut self) {
        if self.realtime.is_some() {
            return;
        }
        self.realtime_hits = 0;
        self.realtime = Some(engine_glue::start_realtime(engine_glue::quick_scan_paths()));
        self.status = "Real-time monitoring starting…".to_string();
    }

    fn stop_realtime(&mut self) {
        if let Some(h) = self.realtime.take() {
            h.stop();
        }
        self.realtime_paths = 0;
        self.status = "Real-time monitoring stopped.".to_string();
    }

    fn do_intel(&mut self) {
        let q = self.intel_query.trim().to_string();
        if q.is_empty() || self.intel_busy {
            return;
        }
        self.intel_busy = true;
        self.intel_lines.clear();
        self.intel_source.clear();
        self.intel_rx = Some(engine_glue::start_intel(q));
    }

    fn refresh_inventory(&mut self) {
        let (h, y, q) = engine_glue::inventory_counts();
        self.hashes = h;
        self.yara = y;
        self.quarantined = q;
    }

    fn reload_quarantine(&mut self) {
        self.q_items = scanner_core::Quarantine::open(engine_glue::quarantine_dir())
            .and_then(|q| q.list())
            .unwrap_or_default();
        self.q_loaded = true;
    }

    fn reload_activity(&mut self) {
        self.activity = history::recent(200);
        self.activity_loaded = true;
    }

    /// Fetch signature feeds on a background thread; applied in `poll`.
    fn do_update(&mut self) {
        if self.updating {
            return;
        }
        self.updating = true;
        self.status = "Updating signatures from feeds…".to_string();
        self.update_rx = Some(engine_glue::start_update());
    }

    fn start(&mut self, targets: Vec<PathBuf>, label: &str) {
        if self.scanning {
            return;
        }
        if targets.is_empty() {
            self.status = format!("No targets found for {label} scan.");
            return;
        }
        self.threats.clear();
        self.scanned = 0;
        self.current.clear();
        self.last = None;
        self.scan_label = label.to_string();
        self.scanning = true;
        self.status = format!("Running {label} scan…");
        self.rx = Some(engine_glue::start_scan(targets));
        self.view = View::Scan;
    }

    fn apply_advice(&mut self, a: Advice) {
        match a {
            Advice::QuickScan => self.start(engine_glue::quick_scan_paths(), "Quick"),
            Advice::Update => self.do_update(),
            Advice::Quarantine => self.view = View::Quarantine,
            Advice::Review => self.view = View::Scan,
        }
    }

    /// Contextual recommendations computed from real state (Bitdefender-style).
    fn recommendations(&self) -> Vec<(String, Option<Advice>)> {
        let mut v = Vec::new();
        let threats = self.last.map(|d| d.malicious + d.suspicious).unwrap_or(0);
        if threats > 0 {
            v.push((
                format!("{threats} detection(s) in your last scan — review and quarantine."),
                Some(Advice::Review),
            ));
        }
        if self.quarantined > 0 {
            v.push((
                format!("{} item(s) waiting in Quarantine.", self.quarantined),
                Some(Advice::Quarantine),
            ));
        }
        if self.last_scan_unix == 0 {
            v.push((
                "You haven't run a scan yet — start with a Quick Scan.".to_string(),
                Some(Advice::QuickScan),
            ));
        }
        if self.last_update_unix == 0 {
            v.push((
                "Update signatures to pull the latest threat intelligence.".to_string(),
                Some(Advice::Update),
            ));
        }
        if v.is_empty() {
            v.push((
                "You're all set — protection is active and definitions are loaded.".to_string(),
                None,
            ));
        }
        v
    }

    fn poll(&mut self, ctx: &egui::Context) {
        let mut finished = false;
        if let Some(rx) = &self.rx {
            loop {
                match rx.try_recv() {
                    Ok(ScanMsg::Progress { scanned, current }) => {
                        self.scanned = scanned;
                        self.current = current;
                    }
                    Ok(ScanMsg::Threat(r)) => {
                        self.scanned += 1;
                        if self.threats.len() < 5000 {
                            self.threats.push(*r);
                        }
                    }
                    Ok(ScanMsg::Done {
                        files,
                        malicious,
                        suspicious,
                        ms,
                        bytes,
                    }) => {
                        self.last = Some(Done {
                            files,
                            malicious,
                            suspicious,
                            ms,
                            bytes,
                        });
                        self.last_scan_unix = now_unix();
                        self.scanning = false;
                        self.status = format!(
                            "{} scan complete — {malicious} malicious, {suspicious} suspicious in {files} files",
                            self.scan_label
                        );
                        finished = true;
                    }
                    Ok(ScanMsg::Failed(e)) => {
                        self.scanning = false;
                        self.status = format!("Scan failed: {e}");
                        finished = true;
                    }
                    Err(TryRecvError::Empty) => break,
                    Err(TryRecvError::Disconnected) => {
                        self.scanning = false;
                        finished = true;
                        break;
                    }
                }
            }
        }
        if finished {
            self.rx = None;
            self.refresh_inventory();
            self.activity_loaded = false;
        }

        // Drain a background feed update, if running.
        if let Some(rx) = &self.update_rx {
            match rx.try_recv() {
                Ok(report) => {
                    self.updating = false;
                    self.update_rx = None;
                    self.refresh_inventory();
                    self.sig_source = engine_glue::signatures_source();
                    self.last_update_unix = now_unix();
                    self.activity_loaded = false;
                    let detail = report.messages.join(" · ");
                    self.status = format!(
                        "Update complete — {detail}  →  {} hash signatures, {} YARA files",
                        self.hashes, self.yara
                    );
                }
                Err(TryRecvError::Empty) => {}
                Err(TryRecvError::Disconnected) => {
                    self.updating = false;
                    self.update_rx = None;
                    self.status = "Update failed.".to_string();
                }
            }
        }

        // Drain real-time monitor events (collect first to avoid borrow issues).
        let mut rt_events = Vec::new();
        if let Some(handle) = &self.realtime {
            while let Ok(msg) = handle.rx.try_recv() {
                rt_events.push(msg);
            }
        }
        for msg in rt_events {
            match msg {
                engine_glue::RealtimeMsg::Started(n) => {
                    self.realtime_paths = n;
                    self.status = format!("Real-time monitoring active — watching {n} folder(s).");
                }
                engine_glue::RealtimeMsg::Detection(r) => {
                    self.realtime_hits += 1;
                    self.status = format!("Real-time: detection in {}", r.path);
                    if self.threats.len() < 5000 {
                        self.threats.push(*r);
                    }
                    self.activity_loaded = false;
                }
                engine_glue::RealtimeMsg::Error(e) => {
                    self.status = format!("Real-time error: {e}");
                    self.realtime = None;
                }
            }
        }

        // Drain a threat-intel lookup, if running.
        let intel_result = self.intel_rx.as_ref().and_then(|rx| rx.try_recv().ok());
        if let Some(result) = intel_result {
            self.intel_busy = false;
            self.intel_rx = None;
            match result {
                Ok(reports) => {
                    let known = reports.iter().filter(|r| r.found).count();
                    self.intel_source =
                        format!("{} provider(s) · {known} with a record", reports.len());
                    let mut lines = Vec::new();
                    for r in reports {
                        lines.push(format!(
                            "── {} · {} ──",
                            r.source,
                            if r.found { "KNOWN" } else { "no record" }
                        ));
                        lines.extend(r.lines);
                    }
                    self.intel_lines = lines;
                }
                Err(e) => {
                    self.intel_source = "Lookup failed".to_string();
                    self.intel_lines = vec![e];
                }
            }
        }

        if self.scanning || self.updating || self.realtime.is_some() || self.intel_busy {
            ctx.request_repaint();
        }
    }
}

impl eframe::App for TalosApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        self.poll(ctx);

        // Upload the bronze-guardian emblem to a texture once.
        if self.hero_tex.is_none() {
            let img = egui::ColorImage::from_rgba_unmultiplied(
                [256, 256],
                include_bytes!("../assets/talos_hero.rgba"),
            );
            self.hero_tex = Some(ctx.load_texture("talos_hero", img, egui::TextureOptions::LINEAR));
        }

        egui::SidePanel::left("nav")
            .exact_width(212.0)
            .resizable(false)
            .frame(egui::Frame::none().fill(BG).inner_margin(16.0))
            .show(ctx, |ui| self.sidebar(ui));

        egui::CentralPanel::default()
            .frame(egui::Frame::none().fill(PANEL).inner_margin(22.0))
            .show(ctx, |ui| {
                egui::ScrollArea::vertical()
                    .auto_shrink([false, false])
                    .show(ui, |ui| match self.view {
                        View::Dashboard => self.dashboard(ui),
                        View::Protection => self.protection(ui),
                        View::Scan => self.scan_view(ui),
                        View::Quarantine => self.quarantine_view(ui),
                        View::Activity => self.activity_view(ui),
                        View::Intel => self.intel_view(ui),
                        View::Settings => self.settings_view(ui),
                        View::About => self.about(ui),
                    });
            });
    }
}

impl TalosApp {
    fn sidebar(&mut self, ui: &mut egui::Ui) {
        let hero = self.hero_tex.clone();
        ui.add_space(4.0);
        ui.horizontal(|ui| {
            if let Some(tex) = &hero {
                ui.add(egui::Image::new(egui::load::SizedTexture::new(
                    tex.id(),
                    egui::vec2(40.0, 40.0),
                )));
                ui.add_space(2.0);
            }
            ui.vertical(|ui| {
                ui.label(RichText::new("TALOS").color(ACCENT).size(23.0).strong());
                ui.label(RichText::new("Endpoint Protection").color(DIM).size(11.0));
            });
        });
        ui.add_space(16.0);

        nav_section(ui, "SECURITY");
        nav(ui, &mut self.view, View::Dashboard, "Dashboard");
        nav(ui, &mut self.view, View::Protection, "Protection");
        nav(ui, &mut self.view, View::Scan, "Scan");
        ui.add_space(10.0);
        nav_section(ui, "MANAGE");
        nav(ui, &mut self.view, View::Quarantine, "Quarantine");
        nav(ui, &mut self.view, View::Activity, "Activity");
        nav(ui, &mut self.view, View::Intel, "Threat Intel");
        ui.add_space(10.0);
        nav_section(ui, "SYSTEM");
        nav(ui, &mut self.view, View::Settings, "Settings");
        nav(ui, &mut self.view, View::About, "About");

        ui.with_layout(egui::Layout::bottom_up(egui::Align::Min), |ui| {
            ui.add_space(4.0);
            ui.label(
                RichText::new(format!("v{}", self.version))
                    .color(DIM)
                    .size(11.0),
            );
            match &self.tenant {
                Some(t) => ui.label(
                    RichText::new(format!("Managed · {t}"))
                        .color(GREEN)
                        .size(11.0),
                ),
                None => ui.label(RichText::new("Unmanaged (local)").color(DIM).size(11.0)),
            };
        });
    }

    fn dashboard(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Dashboard");

        let threats = self.last.map(|d| d.malicious + d.suspicious).unwrap_or(0);
        let (status_col, title, subtitle) = if self.scanning {
            (AMBER, "Scan in progress", "Talos is inspecting your files…")
        } else if threats > 0 {
            (
                ACCENT,
                "Threats need attention",
                "Review the Scan view and quarantine the findings.",
            )
        } else {
            let sub = if self.realtime.is_some() {
                "Real-time monitoring active · on-demand engine ready"
            } else {
                "On-demand engine ready · enable Real-time in Protection"
            };
            (GREEN, "You're protected", sub)
        };

        // Hero protection-status banner: bronze guardian + status + action.
        let hero = self.hero_tex.clone();
        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                if let Some(tex) = &hero {
                    ui.add(egui::Image::new(egui::load::SizedTexture::new(
                        tex.id(),
                        egui::vec2(118.0, 118.0),
                    )));
                    ui.add_space(14.0);
                } else {
                    ui.label(RichText::new("●").color(status_col).size(46.0));
                    ui.add_space(12.0);
                }
                ui.vertical(|ui| {
                    ui.horizontal(|ui| {
                        ui.label(RichText::new("●").color(status_col).size(16.0));
                        ui.label(RichText::new(title).color(TEXT).size(24.0).strong());
                    });
                    ui.label(RichText::new(subtitle).color(DIM).size(13.0));
                    ui.add_space(2.0);
                    ui.label(
                        RichText::new("Talos — the bronze guardian")
                            .color(AMBER)
                            .size(11.0)
                            .italics(),
                    );
                });
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    let label = if self.scanning {
                        "Scanning…"
                    } else {
                        "Quick Scan"
                    };
                    let btn = egui::Button::new(
                        RichText::new(label)
                            .color(Color32::WHITE)
                            .size(15.0)
                            .strong(),
                    )
                    .fill(ACCENT)
                    .min_size(egui::vec2(150.0, 40.0));
                    if ui.add_enabled(!self.scanning, btn).clicked() {
                        self.start(engine_glue::quick_scan_paths(), "Quick");
                    }
                });
            });
        });

        ui.add_space(12.0);

        // At-a-glance metrics: an even, responsive row of uniform tiles.
        let definitions = (self.hashes + self.yara).to_string();
        let last_scan = if self.last_scan_unix == 0 {
            "never".to_string()
        } else {
            time_ago(self.last_scan_unix)
        };
        let (threats_val, threats_col) = match self.last {
            Some(d) if d.malicious + d.suspicious > 0 => {
                ((d.malicious + d.suspicious).to_string(), ACCENT)
            }
            Some(_) => ("0".to_string(), GREEN),
            None => ("—".to_string(), DIM),
        };
        let quar_col = if self.quarantined > 0 { AMBER } else { TEXT };
        ui.columns(4, |c| {
            stat_tile(
                &mut c[0],
                "Definitions",
                &definitions,
                TEXT,
                "signatures & rules",
            );
            stat_tile(&mut c[1], "Last scan", &last_scan, TEXT, "most recent");
            stat_tile(&mut c[2], "Threats", &threats_val, threats_col, "last scan");
            stat_tile(
                &mut c[3],
                "Quarantine",
                &self.quarantined.to_string(),
                quar_col,
                "isolated",
            );
        });

        ui.add_space(12.0);

        // Security advisor — contextual recommendations.
        let recs = self.recommendations();
        let mut chosen: Option<Advice> = None;
        card(ui, CARD, |ui| {
            ui.label(
                RichText::new("Security advisor")
                    .color(TEXT)
                    .size(16.0)
                    .strong(),
            );
            ui.label(
                RichText::new("Recommended actions for your system.")
                    .color(DIM)
                    .size(12.0),
            );
            ui.add_space(8.0);
            for (text, advice) in &recs {
                ui.horizontal(|ui| {
                    let dot = if advice.is_some() { AMBER } else { GREEN };
                    ui.label(RichText::new("●").color(dot).size(11.0));
                    ui.label(RichText::new(text).color(TEXT).size(13.0));
                    if let Some(a) = advice {
                        ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                            if secondary_button(ui, advice_label(*a)).clicked() {
                                chosen = Some(*a);
                            }
                        });
                    }
                });
            }
        });
        if let Some(a) = chosen {
            self.apply_advice(a);
        }

        ui.add_space(12.0);

        // Definitions + Update.
        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                ui.vertical(|ui| {
                    ui.label(RichText::new("Definitions").color(TEXT).size(16.0).strong());
                    ui.label(
                        RichText::new(format!("Source: {}", self.sig_source))
                            .color(DIM)
                            .size(12.0),
                    );
                    ui.label(
                        RichText::new(format!(
                            "{} hash signatures · {} YARA rule files",
                            self.hashes, self.yara
                        ))
                        .color(DIM)
                        .size(12.0),
                    );
                    let updated = if self.last_update_unix == 0 {
                        "not checked this session".to_string()
                    } else {
                        time_ago(self.last_update_unix)
                    };
                    ui.label(
                        RichText::new(format!("Last updated: {updated}"))
                            .color(DIM)
                            .size(12.0),
                    );
                });
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    let label = if self.updating {
                        "Updating…"
                    } else {
                        "Update"
                    };
                    let btn =
                        egui::Button::new(RichText::new(label).color(Color32::WHITE).strong())
                            .fill(ACCENT)
                            .min_size(egui::vec2(150.0, 38.0));
                    if ui.add_enabled(!self.updating, btn).clicked() {
                        self.do_update();
                    }
                });
            });
            ui.add_space(4.0);
            ui.label(
                RichText::new(
                    "Fetches openly-licensed feeds (abuse.ch hashes + open YARA rules) into \
                     your local store and reloads the engine. Signed delta channel is on the roadmap.",
                )
                .color(DIM)
                .size(11.0),
            );
        });

        ui.add_space(10.0);
        ui.label(RichText::new(&self.status).color(DIM).size(12.0));
    }

    fn protection(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Protection");
        ui.label(
            RichText::new(
                "Layered on-demand protection. Real-time modules arrive with the Phase-2 \
                 kernel sensor (see docs/01).",
            )
            .color(DIM)
            .size(12.0),
        );
        ui.add_space(10.0);

        nav_section(ui, "ACTIVE");

        // Real-time on-access monitoring (user-mode) — actually starts/stops a
        // folder watcher; not the kernel minifilter (that's Phase 2).
        let mut rt_on = self.realtime.is_some();
        let rt_desc = if self.realtime.is_some() {
            format!(
                "ACTIVE — on-access scan + auto-quarantine · {} folder(s) · {} hit(s)",
                self.realtime_paths, self.realtime_hits
            )
        } else {
            "On-access scan + instant auto-quarantine of new/changed files. Pre-execution \
             blocking = Phase-2 minifilter (Windows) or `talos watch --enforce` (Linux/fanotify)."
                .to_string()
        };
        if module_toggle(ui, "Real-time Protection", &rt_desc, &mut rt_on) {
            if rt_on {
                self.start_realtime();
            } else {
                self.stop_realtime();
            }
        }

        module_card(
            ui,
            "Antimalware Engine",
            "Exact SHA-256 hash signatures for known-bad files.",
            ModuleStatus::Active,
        );
        module_card(
            ui,
            "YARA Rules",
            "Pattern matching: web shells, malicious PowerShell, offensive tooling.",
            ModuleStatus::Active,
        );

        // Real toggles wired to settings (persisted + applied on next scan).
        let mut h = self.config.heuristics;
        if module_toggle(
            ui,
            "Heuristic Analysis",
            "Static PE checks: packing, process-injection imports, W^X sections.",
            &mut h,
        ) {
            self.config.heuristics = h;
            self.config.save();
        }
        let mut b = self.config.behavior;
        if module_toggle(
            ui,
            "Behavioral Analysis",
            "CAPA-style capability inference from imports & strings, MITRE ATT&CK-tagged.",
            &mut b,
        ) {
            self.config.behavior = b;
            self.config.save();
        }
        let mut a = self.config.scan_archives;
        if module_toggle(
            ui,
            "Archive Inspection",
            "Look inside ZIP archives (zip-bomb-guarded).",
            &mut a,
        ) {
            self.config.scan_archives = a;
            self.config.save();
        }

        module_card(
            ui,
            "Quarantine Vault",
            "Isolate detected files and restore false positives.",
            ModuleStatus::Active,
        );
        module_card(
            ui,
            "Signature Updates",
            "abuse.ch malware hashes + open YARA feeds, on demand.",
            ModuleStatus::Active,
        );

        ui.add_space(12.0);
        nav_section(ui, "ROADMAP · PHASE 2 (KERNEL SENSOR)");
        for (name, desc) in [
            (
                "Pre-execution Blocking",
                "Kernel minifilter that blocks malicious file I/O before it runs.",
            ),
            (
                "Web Protection",
                "Block malicious URLs and phishing in the browser.",
            ),
            ("Firewall", "Application-aware network filtering (WFP)."),
            (
                "Ransomware Remediation",
                "Behavioral rollback of unauthorized encryption.",
            ),
            (
                "Banking & Payment",
                "Hardened isolated browser for transactions.",
            ),
        ] {
            module_card(ui, name, desc, ModuleStatus::Roadmap);
        }
    }

    fn scan_view(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Scan");

        ui.add_enabled_ui(!self.scanning, |ui| {
            ui.horizontal(|ui| {
                if primary_button(ui, "Quick Scan").clicked() {
                    self.start(engine_glue::quick_scan_paths(), "Quick");
                }
                if secondary_button(ui, "Full Scan").clicked() {
                    self.start(engine_glue::full_scan_roots(), "Full");
                }
            });
            ui.add_space(8.0);
            ui.horizontal(|ui| {
                ui.label(RichText::new("Custom path:").color(DIM));
                ui.add(
                    egui::TextEdit::singleline(&mut self.custom_path)
                        .desired_width(420.0)
                        .hint_text("C:\\Users\\me\\Downloads"),
                );
                if secondary_button(ui, "Scan").clicked() {
                    let trimmed = self.custom_path.trim().to_string();
                    let p = PathBuf::from(&trimmed);
                    if trimmed.is_empty() {
                        self.status = "Enter a path to scan.".to_string();
                    } else if !p.exists() {
                        self.status = format!("Path does not exist: {trimmed}");
                    } else {
                        self.start(vec![p], "Custom");
                    }
                }
            });
        });

        ui.add_space(10.0);
        card(ui, CARD, |ui| {
            if self.scanning {
                ui.horizontal(|ui| {
                    ui.add(egui::Spinner::new().color(ACCENT));
                    ui.label(
                        RichText::new(format!(
                            "Scanning… {} files · {} threats",
                            self.scanned,
                            self.threats.len()
                        ))
                        .color(TEXT)
                        .size(15.0),
                    );
                });
                ui.label(
                    RichText::new(truncate(&self.current, 80))
                        .color(DIM)
                        .size(11.0),
                );
            } else if let Some(d) = self.last {
                let mibps = if d.ms > 0 {
                    (d.bytes as f64 / 1_048_576.0) / (d.ms as f64 / 1000.0)
                } else {
                    0.0
                };
                ui.label(
                    RichText::new(format!(
                        "{} scan: {} files · {} malicious · {} suspicious · {} ms · {:.1} MiB/s",
                        self.scan_label, d.files, d.malicious, d.suspicious, d.ms, mibps
                    ))
                    .color(TEXT),
                );
            } else {
                ui.label(RichText::new("Choose a scan to begin.").color(DIM));
            }
        });

        if !self.threats.is_empty() {
            ui.add_space(8.0);
            let malicious = self.threats.iter().filter(|r| r.is_malicious()).count();
            let mut do_quarantine = false;
            ui.horizontal(|ui| {
                ui.label(
                    RichText::new(format!("Detections ({})", self.threats.len()))
                        .color(TEXT)
                        .strong(),
                );
                if malicious > 0
                    && !self.scanning
                    && secondary_button(ui, &format!("Quarantine {malicious}")).clicked()
                {
                    do_quarantine = true;
                }
            });
            if do_quarantine {
                match engine_glue::quarantine_reports(&self.threats) {
                    Ok(n) => {
                        self.status = format!("Quarantined {n} item(s).");
                        history::record("quarantine", format!("Quarantined {n} item(s)"));
                        self.threats.retain(|r| !r.is_malicious());
                        self.q_loaded = false;
                        self.activity_loaded = false;
                        self.refresh_inventory();
                    }
                    Err(e) => self.status = format!("Quarantine failed: {e}"),
                }
            }

            egui::ScrollArea::vertical()
                .auto_shrink([false, false])
                .show(ui, |ui| {
                    for r in &self.threats {
                        for d in &r.detections {
                            ui.horizontal(|ui| {
                                ui.label(
                                    RichText::new(sev_tag(d.severity))
                                        .color(sev_color(d.severity))
                                        .strong(),
                                );
                                ui.label(RichText::new(&r.path).color(TEXT).size(12.0));
                                ui.label(
                                    RichText::new(format!("→ {}", d.name)).color(DIM).size(12.0),
                                );
                            });
                        }
                    }
                });
        }
    }

    fn quarantine_view(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Quarantine");
        if !self.q_loaded {
            self.reload_quarantine();
        }
        ui.horizontal(|ui| {
            if secondary_button(ui, "Refresh").clicked() {
                self.reload_quarantine();
            }
            ui.label(RichText::new(format!("{} item(s)", self.q_items.len())).color(DIM));
        });
        ui.add_space(6.0);

        if self.q_items.is_empty() {
            card(ui, CARD, |ui| {
                ui.label(RichText::new("Quarantine is empty.").color(DIM));
            });
            return;
        }

        enum Act {
            Restore,
            Purge,
        }
        let mut action: Option<(Act, String)> = None;

        egui::ScrollArea::vertical()
            .auto_shrink([false, false])
            .show(ui, |ui| {
                for item in &self.q_items {
                    card(ui, CARD, |ui| {
                        ui.horizontal(|ui| {
                            ui.vertical(|ui| {
                                ui.label(RichText::new(&item.original_path).color(TEXT).size(12.0));
                                let names: Vec<&str> =
                                    item.detections.iter().map(|d| d.name.as_str()).collect();
                                ui.label(RichText::new(names.join(", ")).color(DIM).size(11.0));
                            });
                            ui.with_layout(
                                egui::Layout::right_to_left(egui::Align::Center),
                                |ui| {
                                    if ui.button(RichText::new("Delete").color(ACCENT)).clicked() {
                                        action = Some((Act::Purge, item.id.clone()));
                                    }
                                    if ui.button("Restore").clicked() {
                                        action = Some((Act::Restore, item.id.clone()));
                                    }
                                },
                            );
                        });
                    });
                }
            });

        if let Some((act, id)) = action {
            if let Ok(store) = scanner_core::Quarantine::open(engine_glue::quarantine_dir()) {
                let _ = match act {
                    Act::Restore => {
                        history::record("quarantine", "Restored an item from quarantine");
                        store.restore(&id, None).map(|_| ())
                    }
                    Act::Purge => {
                        history::record("quarantine", "Deleted an item from quarantine");
                        store.purge(&id)
                    }
                };
            }
            self.status = "Quarantine updated.".to_string();
            self.activity_loaded = false;
            self.reload_quarantine();
            self.refresh_inventory();
        }
    }

    fn activity_view(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Activity");
        if !self.activity_loaded {
            self.reload_activity();
        }
        ui.horizontal(|ui| {
            if secondary_button(ui, "Refresh").clicked() {
                self.reload_activity();
            }
            ui.label(RichText::new(format!("{} event(s)", self.activity.len())).color(DIM));
        });
        ui.add_space(6.0);

        if self.activity.is_empty() {
            card(ui, CARD, |ui| {
                ui.label(
                    RichText::new("No activity yet. Run a scan or update signatures.").color(DIM),
                );
            });
            return;
        }

        egui::ScrollArea::vertical()
            .auto_shrink([false, false])
            .show(ui, |ui| {
                for e in &self.activity {
                    card(ui, CARD, |ui| {
                        ui.horizontal(|ui| {
                            let col = match e.kind.as_str() {
                                "scan" => GREEN,
                                "update" => AMBER,
                                "quarantine" => ACCENT,
                                _ => DIM,
                            };
                            ui.label(RichText::new("●").color(col).size(13.0));
                            ui.add_space(4.0);
                            ui.vertical(|ui| {
                                ui.label(RichText::new(&e.summary).color(TEXT).size(12.0));
                                ui.label(RichText::new(time_ago(e.unix)).color(DIM).size(11.0));
                            });
                        });
                    });
                }
            });
    }

    fn intel_view(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Threat Intelligence");
        ui.label(
            RichText::new(
                "Look up a file's SHA-256 against a free online malware database. Only the \
                 hash is sent — never file contents.",
            )
            .color(DIM)
            .size(12.0),
        );
        ui.add_space(10.0);

        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                ui.add(
                    egui::TextEdit::singleline(&mut self.intel_query)
                        .desired_width(520.0)
                        .hint_text("SHA-256 hash (64 hex characters)"),
                );
                let label = if self.intel_busy {
                    "Looking up…"
                } else {
                    "Look up"
                };
                if ui
                    .add_enabled(
                        !self.intel_busy,
                        egui::Button::new(RichText::new(label).color(Color32::WHITE).strong())
                            .fill(ACCENT)
                            .min_size(egui::vec2(120.0, 32.0)),
                    )
                    .clicked()
                {
                    self.do_intel();
                }
            });
            ui.add_space(4.0);
            ui.label(
                RichText::new(
                    "Queries every provider you have a key for: TALOS_VT_KEY (VirusTotal), \
                     TALOS_ABUSE_KEY (MalwareBazaar), TALOS_MALSHARE_KEY, TALOS_OTX_KEY \
                     (AlienVault), TALOS_HYBRID_KEY (Hybrid Analysis).",
                )
                .color(DIM)
                .size(11.0),
            );
        });

        if !self.intel_lines.is_empty() {
            ui.add_space(10.0);
            card(ui, CARD, |ui| {
                ui.label(
                    RichText::new(format!("Source: {}", self.intel_source))
                        .color(TEXT)
                        .strong(),
                );
                ui.add_space(4.0);
                for line in &self.intel_lines {
                    ui.label(RichText::new(line).color(DIM).size(12.0));
                }
            });
        }
    }

    fn settings_view(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Settings");
        let mut dirty = false;

        // --- Scan engine ---
        card(ui, CARD, |ui| {
            ui.label(RichText::new("Scan engine").color(TEXT).size(16.0).strong());
            ui.add_space(6.0);
            if ui
                .add(
                    egui::Slider::new(&mut self.config.max_size_mib, 1..=1024)
                        .text("Max file size for content/YARA scan (MiB)"),
                )
                .changed()
            {
                dirty = true;
            }
            if ui
                .checkbox(
                    &mut self.config.scan_archives,
                    "Inspect inside ZIP archives",
                )
                .changed()
            {
                dirty = true;
            }
            if ui
                .checkbox(
                    &mut self.config.heuristics,
                    "Static PE heuristics (packing / injection / W^X)",
                )
                .changed()
            {
                dirty = true;
            }
            if ui
                .checkbox(
                    &mut self.config.behavior,
                    "Behavioral analysis (capability inference, MITRE ATT&CK)",
                )
                .changed()
            {
                dirty = true;
            }
            if ui
                .checkbox(&mut self.config.follow_symlinks, "Follow symbolic links")
                .changed()
            {
                dirty = true;
            }
        });
        ui.add_space(10.0);

        // --- Exclusions ---
        card(ui, CARD, |ui| {
            ui.label(RichText::new("Exclusions").color(TEXT).size(16.0).strong());
            ui.label(
                RichText::new("Trusted files or folders to skip during scans.")
                    .color(DIM)
                    .size(12.0),
            );
            ui.add_space(6.0);
            ui.horizontal(|ui| {
                ui.add(
                    egui::TextEdit::singleline(&mut self.new_exclusion)
                        .desired_width(420.0)
                        .hint_text("C:\\path\\to\\trusted  (file or folder)"),
                );
                if secondary_button(ui, "Add").clicked() {
                    let p = self.new_exclusion.trim().to_string();
                    if !p.is_empty() && !self.config.exclusions.contains(&p) {
                        self.config.exclusions.push(p);
                        self.new_exclusion.clear();
                        dirty = true;
                    }
                }
            });
            ui.add_space(4.0);
            let mut remove: Option<usize> = None;
            for (i, ex) in self.config.exclusions.iter().enumerate() {
                ui.horizontal(|ui| {
                    ui.label(RichText::new(ex).color(TEXT).size(12.0));
                    ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                        if ui.button("Remove").clicked() {
                            remove = Some(i);
                        }
                    });
                });
            }
            if let Some(i) = remove {
                self.config.exclusions.remove(i);
                dirty = true;
            }
            if self.config.exclusions.is_empty() {
                ui.label(
                    RichText::new("No exclusions configured.")
                        .color(DIM)
                        .size(12.0),
                );
            }
        });
        ui.add_space(10.0);

        // --- Scheduled scan ---
        card(ui, CARD, |ui| {
            ui.label(
                RichText::new("Scheduled scan")
                    .color(TEXT)
                    .size(16.0)
                    .strong(),
            );
            ui.label(
                RichText::new(
                    "Saved now; runs automatically once the Phase-2 background service ships.",
                )
                .color(DIM)
                .size(11.0),
            );
            ui.add_space(6.0);
            ui.horizontal(|ui| {
                for s in [Schedule::Off, Schedule::Daily, Schedule::Weekly] {
                    if ui
                        .selectable_value(&mut self.config.schedule, s, s.label())
                        .changed()
                    {
                        dirty = true;
                    }
                }
            });
        });

        ui.add_space(8.0);
        ui.label(
            RichText::new("Settings are saved automatically and apply to your next scan.")
                .color(DIM)
                .size(11.0),
        );

        if dirty {
            self.config.save();
        }
    }

    fn about(&mut self, ui: &mut egui::Ui) {
        heading(ui, "About");
        let hero = self.hero_tex.clone();
        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                if let Some(tex) = &hero {
                    ui.add(egui::Image::new(egui::load::SizedTexture::new(
                        tex.id(),
                        egui::vec2(128.0, 128.0),
                    )));
                    ui.add_space(14.0);
                }
                ui.vertical(|ui| {
                    ui.label(
                        RichText::new("Talos EPP — Endpoint Protection Platform")
                            .color(TEXT)
                            .size(16.0)
                            .strong(),
                    );
                    ui.label(RichText::new(format!("Version {}", self.version)).color(DIM));
                    ui.add_space(4.0);
                    ui.label(
                        RichText::new(
                            "Named for Talos — the giant bronze automaton of Greek myth that \
                             circled Crete three times a day to guard it from invaders.",
                        )
                        .color(AMBER)
                        .size(12.0)
                        .italics(),
                    );
                });
            });
            ui.add_space(10.0);
            ui.label(RichText::new("Detection layers").color(TEXT).strong());
            ui.label(RichText::new("• Hash signatures (SHA-256)").color(DIM));
            ui.label(
                RichText::new("• YARA rules (web shells, malicious PowerShell, …)").color(DIM),
            );
            ui.label(
                RichText::new("• Static PE heuristics (packing, injection imports, W^X)")
                    .color(DIM),
            );
            ui.label(
                RichText::new("• Behavioral capability analysis (CAPA-style, MITRE ATT&CK)")
                    .color(DIM),
            );
            ui.label(RichText::new("• ZIP archive inspection (zip-bomb-guarded)").color(DIM));
            ui.label(
                RichText::new("• Real-time on-access protection (scan + auto-quarantine; fanotify blocking on Linux)")
                    .color(DIM),
            );
            ui.label(
                RichText::new("• Threat-intel hash lookup (MalwareBazaar / VirusTotal)").color(DIM),
            );
            ui.add_space(8.0);
            ui.label(
                RichText::new(
                    "Signature feeds: abuse.ch (CC0) + open YARA (DRL) + optional ClamAV (GPL). \
                     See THIRD-PARTY-NOTICES.md. Real-time kernel sensor, ML and cloud are on the \
                     roadmap.",
                )
                .color(DIM),
            );
        });
    }
}

// ---- small widgets / helpers --------------------------------------------

fn nav(ui: &mut egui::Ui, current: &mut View, target: View, label: &str) {
    let selected = *current == target;
    let resp = ui.add_sized(
        [ui.available_width(), 34.0],
        egui::SelectableLabel::new(selected, RichText::new(label).size(15.0)),
    );
    if resp.clicked() {
        *current = target;
    }
}

fn nav_section(ui: &mut egui::Ui, text: &str) {
    ui.label(RichText::new(text).color(DIM).size(10.5).strong());
    ui.add_space(2.0);
}

fn heading(ui: &mut egui::Ui, text: &str) {
    ui.label(RichText::new(text).color(TEXT).size(26.0).strong());
    ui.add_space(12.0);
}

fn card<R>(ui: &mut egui::Ui, fill: Color32, add: impl FnOnce(&mut egui::Ui) -> R) -> R {
    egui::Frame::none()
        .fill(fill)
        .rounding(10.0)
        .inner_margin(16.0)
        .show(ui, add)
        .inner
}

/// A metric tile that fills its column to a uniform size, so a row of them
/// reads as an aligned grid rather than a scatter of differently-sized boxes.
fn stat_tile(ui: &mut egui::Ui, title: &str, value: &str, value_col: Color32, unit: &str) {
    egui::Frame::none()
        .fill(CARD)
        .rounding(10.0)
        .inner_margin(14.0)
        .show(ui, |ui| {
            ui.set_min_width(ui.available_width());
            ui.set_min_height(58.0);
            ui.vertical(|ui| {
                ui.label(
                    RichText::new(title.to_uppercase())
                        .color(DIM)
                        .size(10.5)
                        .strong(),
                );
                ui.add_space(3.0);
                ui.label(RichText::new(value).color(value_col).size(23.0).strong());
                ui.label(RichText::new(unit).color(DIM).size(10.5));
            });
        });
}

#[derive(Clone, Copy)]
enum ModuleStatus {
    Active,
    Roadmap,
}

/// A protection-module row: title + description on the left, a status dot on
/// the right (Malwarebytes / Bitdefender Protection-tab style).
fn module_card(ui: &mut egui::Ui, name: &str, desc: &str, status: ModuleStatus) {
    card(ui, CARD, |ui| {
        ui.horizontal(|ui| {
            ui.vertical(|ui| {
                ui.label(RichText::new(name).color(TEXT).size(15.0).strong());
                ui.label(RichText::new(desc).color(DIM).size(12.0));
            });
            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                let (txt, col) = match status {
                    ModuleStatus::Active => ("ACTIVE", GREEN),
                    ModuleStatus::Roadmap => ("ROADMAP", DIM),
                };
                ui.label(
                    RichText::new(format!("● {txt}"))
                        .color(col)
                        .size(12.0)
                        .strong(),
                );
            });
        });
    });
    ui.add_space(8.0);
}

/// Like [`module_card`] but with a real on/off toggle; returns whether the
/// toggle changed this frame.
fn module_toggle(ui: &mut egui::Ui, name: &str, desc: &str, on: &mut bool) -> bool {
    let mut changed = false;
    card(ui, CARD, |ui| {
        ui.horizontal(|ui| {
            ui.vertical(|ui| {
                ui.label(RichText::new(name).color(TEXT).size(15.0).strong());
                ui.label(RichText::new(desc).color(DIM).size(12.0));
            });
            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                let label = if *on { "On" } else { "Off" };
                if ui.toggle_value(on, label).changed() {
                    changed = true;
                }
            });
        });
    });
    ui.add_space(8.0);
    changed
}

fn primary_button(ui: &mut egui::Ui, text: &str) -> egui::Response {
    ui.add_sized(
        [ui.available_width().min(220.0), 40.0],
        egui::Button::new(
            RichText::new(text)
                .color(Color32::WHITE)
                .size(15.0)
                .strong(),
        )
        .fill(ACCENT),
    )
}

fn secondary_button(ui: &mut egui::Ui, text: &str) -> egui::Response {
    ui.add_sized(
        [120.0, 34.0],
        egui::Button::new(RichText::new(text).color(TEXT)),
    )
}

fn advice_label(a: Advice) -> &'static str {
    match a {
        Advice::QuickScan => "Quick Scan",
        Advice::Update => "Update",
        Advice::Quarantine => "Review",
        Advice::Review => "Open Scan",
    }
}

fn sev_color(s: Severity) -> Color32 {
    match s {
        Severity::Low => DIM,
        Severity::Medium => AMBER,
        Severity::High => Color32::from_rgb(0xff, 0x6a, 0x3d),
        Severity::Critical => ACCENT,
    }
}

fn sev_tag(s: Severity) -> &'static str {
    match s {
        Severity::Low => "LOW ",
        Severity::Medium => "MED ",
        Severity::High => "HIGH",
        Severity::Critical => "CRIT",
    }
}

fn truncate(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        s.to_string()
    } else {
        let kept: String = s
            .chars()
            .rev()
            .take(max)
            .collect::<Vec<_>>()
            .into_iter()
            .rev()
            .collect();
        format!("…{kept}")
    }
}

fn now_unix() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

fn time_ago(then: u64) -> String {
    let secs = now_unix().saturating_sub(then);
    match secs {
        0..=59 => "just now".to_string(),
        60..=3599 => format!("{} min ago", secs / 60),
        3600..=86_399 => format!("{} h ago", secs / 3600),
        _ => format!("{} d ago", secs / 86_400),
    }
}
