//! Talos EPP — desktop GUI (egui/eframe). A self-contained, dark "security
//! console" front-end over the same engine the CLI uses.
//!
//! The layout borrows the patterns that make the leading suites approachable:
//! a Bitdefender-style **Security Advisor** with contextual recommendations, a
//! Malwarebytes-style **Protection module grid**, an ESET/Kaspersky-style
//! grouped navigation, a persisted **Activity** log, and a power-user
//! **Settings** panel whose toggles genuinely change how scans run.
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod agent_link;
mod config;
mod engine_glue;
mod history;

use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc::{Receiver, TryRecvError};
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use eframe::egui;
use egui::{Color32, RichText};
use scanner_core::{ScanReport, Severity, BASELINE_BLOCKS, BASELINE_PORTS};

use config::{Schedule, TalosConfig};
use engine_glue::ScanMsg;

// ---- palette -------------------------------------------------------------
const BG: Color32 = Color32::from_rgb(0x09, 0x0b, 0x10);
const PANEL: Color32 = Color32::from_rgb(0x0e, 0x11, 0x17);
const CARD: Color32 = Color32::from_rgb(0x15, 0x19, 0x21);
const TEXT: Color32 = Color32::from_rgb(0xf0, 0xf2, 0xf5);
const DIM: Color32 = Color32::from_rgb(0x8a, 0x94, 0xa3);
const ACCENT: Color32 = Color32::from_rgb(0xff, 0x2d, 0x3a); // Vibrant Talos red
const GREEN: Color32 = Color32::from_rgb(0x00, 0xe6, 0x76);
const AMBER: Color32 = Color32::from_rgb(0xff, 0x91, 0x00);

fn main() -> eframe::Result<()> {
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_inner_size([1040.0, 700.0])
            .with_min_inner_size([880.0, 600.0])
            .with_icon(std::sync::Arc::new(load_icon()))
            .with_title("Talos EPP — Endpoint Protection"),
        ..Default::default()
    };
    eframe::run_native(
        "Talos EPP",
        options,
        Box::new(|cc| {
            install_theme(&cc.egui_ctx);
            Ok(Box::new(TalosApp::new()))
        }),
    )
}

/// The app icon for the window/taskbar, as raw 64x64 RGBA generated by
/// `tools/make_icon.py` (the same artwork embedded into the .exe).
fn load_icon() -> egui::IconData {
    egui::IconData {
        rgba: include_bytes!("../assets/icon-64.rgba").to_vec(),
        width: 64,
        height: 64,
    }
}

fn install_theme(ctx: &egui::Context) {
    let mut v = egui::Visuals::dark();
    v.panel_fill = PANEL;
    v.window_fill = PANEL;
    v.extreme_bg_color = BG;
    v.override_text_color = Some(TEXT);
    v.selection.bg_fill = ACCENT.linear_multiply(0.3);
    v.widgets.hovered.bg_fill = CARD;
    v.widgets.hovered.rounding = egui::Rounding::same(4.0);
    v.widgets.inactive.bg_fill = PANEL;
    v.widgets.inactive.rounding = egui::Rounding::same(4.0);
    v.widgets.active.bg_fill = ACCENT;
    v.widgets.active.rounding = egui::Rounding::same(4.0);
    v.window_rounding = egui::Rounding::same(0.0); // Sharp, enterprise edges
    ctx.set_visuals(v);

    let mut style = (*ctx.style()).clone();
    style.spacing.item_spacing = egui::vec2(12.0, 10.0);
    style.spacing.button_padding = egui::vec2(20.0, 12.0);
    style.spacing.interact_size.y = 32.0;

    // Enterprise typography setup
    use egui::{FontFamily, FontId, TextStyle};
    let font_definitions = egui::FontDefinitions::default();

    // Use system sans-serif for that clean enterprise look
    style.text_styles = [
        (
            TextStyle::Heading,
            FontId::new(24.0, FontFamily::Proportional),
        ),
        (TextStyle::Body, FontId::new(14.0, FontFamily::Proportional)),
        (
            TextStyle::Monospace,
            FontId::new(13.0, FontFamily::Monospace),
        ),
        (
            TextStyle::Button,
            FontId::new(14.0, FontFamily::Proportional),
        ),
        (
            TextStyle::Small,
            FontId::new(11.0, FontFamily::Proportional),
        ),
    ]
    .into();

    ctx.set_fonts(font_definitions);
    ctx.set_style(style);
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum View {
    Dashboard,
    Protection,
    Scan,
    Quarantine,
    Activity,
    Intel,
    Settings,
    About,
}

#[derive(Clone, Copy)]
struct Done {
    files: u64,
    malicious: u64,
    suspicious: u64,
    ms: u64,
    bytes: u64,
}

/// A one-click action the Security Advisor can recommend.
#[derive(Clone, Copy)]
enum Advice {
    QuickScan,
    Update,
    Quarantine,
    Review,
}

struct TalosApp {
    view: View,
    version: String,
    tenant: Option<String>,
    config: TalosConfig,
    hashes: usize,
    yara: usize,
    quarantined: usize,

    custom_path: String,
    new_exclusion: String,
    firewall_ip: String,
    new_port_rule: String,
    new_ip_rule: String,

    rx: Option<Receiver<ScanMsg>>,
    /// Raise to stop the running scan early (drives `ScanOptions::cancel`).
    scan_stop: Option<Arc<AtomicBool>>,
    scanning: bool,
    scan_label: String,
    scanned: u64,
    current: String,
    threats: Vec<ScanReport>,
    last: Option<Done>,
    last_scan_unix: u64,
    status: String,
    sig_source: String,
    last_update_unix: u64,
    updating: bool,
    update_rx: Option<Receiver<scanner_core::UpdateReport>>,

    q_items: Vec<scanner_core::QuarantineEntry>,
    q_loaded: bool,

    activity: Vec<history::Event>,
    activity_loaded: bool,

    realtime: Option<engine_glue::RealtimeHandle>,
    realtime_paths: usize,
    realtime_hits: u64,

    /// Live status of the always-on agent service (if installed/running),
    /// polled over IPC. `None` means no agent is reachable.
    agent_status: Option<talos_ipc::Status>,
    agent_rx: Option<Receiver<Option<talos_ipc::Status>>>,
    agent_polled_at: u64,
    /// The agent service's activity log (when present), polled over IPC.
    agent_events: Vec<talos_ipc::Event>,
    agent_events_rx: Option<Receiver<Vec<talos_ipc::Event>>>,
    agent_events_polled_at: u64,

    intel_query: String,
    intel_source: String,
    intel_lines: Vec<String>,
    intel_busy: bool,
    intel_rx: Option<Receiver<Result<Vec<scanner_core::IntelReport>, String>>>,

    /// The Talos bronze-guardian emblem, lazily uploaded as a GPU texture.
    hero_tex: Option<egui::TextureHandle>,

    /// In-process firewall / web-protection control, used when no privileged
    /// agent is present. `admin_rx` carries the result of a running action;
    /// `local_*` track state the agent would otherwise report.
    admin_rx: Option<Receiver<engine_glue::AdminMsg>>,
    admin_busy: bool,
    local_fw_on: bool,
    local_fw_blocked: usize,
    local_web_on: bool,
    local_web_blocked: usize,
}

impl TalosApp {
    fn new() -> Self {
        let (hashes, yara, quarantined) = engine_glue::inventory_counts();
        Self {
            view: View::Dashboard,
            version: env!("CARGO_PKG_VERSION").to_string(),
            tenant: std::env::var("TALOS_TENANT").ok().filter(|s| !s.is_empty()),
            config: TalosConfig::load(),
            hashes,
            yara,
            quarantined,
            custom_path: String::new(),
            new_exclusion: String::new(),
            firewall_ip: String::new(),
            new_port_rule: String::new(),
            new_ip_rule: String::new(),
            rx: None,
            scan_stop: None,
            scanning: false,
            scan_label: String::new(),
            scanned: 0,
            current: String::new(),
            threats: Vec::new(),
            last: None,
            last_scan_unix: 0,
            status: "Ready.".to_string(),
            sig_source: engine_glue::signatures_source(),
            last_update_unix: 0,
            updating: false,
            update_rx: None,
            q_items: Vec::new(),
            q_loaded: false,
            activity: Vec::new(),
            activity_loaded: false,
            realtime: None,
            realtime_paths: 0,
            realtime_hits: 0,
            agent_status: None,
            agent_rx: None,
            agent_polled_at: 0,
            agent_events: Vec::new(),
            agent_events_rx: None,
            agent_events_polled_at: 0,
            intel_query: String::new(),
            intel_source: String::new(),
            intel_lines: Vec::new(),
            intel_busy: false,
            intel_rx: None,
            hero_tex: None,
            admin_rx: None,
            admin_busy: false,
            local_fw_on: false,
            local_fw_blocked: 0,
            local_web_on: false,
            local_web_blocked: 0,
        }
    }

    fn start_realtime(&mut self) {
        if self.realtime.is_some() {
            return;
        }
        self.realtime_hits = 0;
        self.realtime = Some(engine_glue::start_realtime(engine_glue::quick_scan_paths()));
        self.status = "Real-time monitoring starting…".to_string();
    }

    fn stop_realtime(&mut self) {
        if let Some(h) = self.realtime.take() {
            h.stop();
        }
        self.realtime_paths = 0;
        self.status = "Real-time monitoring stopped.".to_string();
    }

    fn do_intel(&mut self) {
        let q = self.intel_query.trim().to_string();
        if q.is_empty() || self.intel_busy {
            return;
        }
        self.intel_busy = true;
        self.intel_lines.clear();
        self.intel_source.clear();
        self.intel_rx = Some(engine_glue::start_intel(q));
    }

    fn refresh_inventory(&mut self) {
        let (h, y, q) = engine_glue::inventory_counts();
        self.hashes = h;
        self.yara = y;
        self.quarantined = q;
    }

    fn reload_quarantine(&mut self) {
        self.q_items = scanner_core::Quarantine::open(engine_glue::quarantine_dir())
            .and_then(|q| q.list())
            .unwrap_or_default();
        self.q_loaded = true;
    }

    fn reload_activity(&mut self) {
        self.activity = history::recent(200);
        self.activity_loaded = true;
    }

    /// Fetch signature feeds on a background thread; applied in `poll`.
    fn do_update(&mut self) {
        if self.updating {
            return;
        }
        self.updating = true;
        self.status = "Updating signatures from feeds…".to_string();
        self.update_rx = Some(engine_glue::start_update());
    }

    fn start(&mut self, targets: Vec<PathBuf>, label: &str) {
        if self.scanning {
            return;
        }
        if targets.is_empty() {
            self.status = format!("No targets found for {label} scan.");
            return;
        }
        self.threats.clear();
        self.scanned = 0;
        self.current.clear();
        self.last = None;
        self.scan_label = label.to_string();
        self.scanning = true;
        self.status = format!("Running {label} scan…");
        // A Full Scan is deliberately thorough and re-reads every file; Quick and
        // Custom scans use the incremental cache to skip unchanged clean files.
        let use_cache = label != "Full";
        let (rx, stop) = engine_glue::start_scan(targets, use_cache);
        self.rx = Some(rx);
        self.scan_stop = Some(stop);
        self.view = View::Scan;
    }

    /// Request that the running scan stop (it ends promptly with partial results).
    fn stop_scan(&mut self) {
        if let Some(stop) = &self.scan_stop {
            stop.store(true, Ordering::Relaxed);
            self.status = "Stopping scan — finishing the files in flight…".to_string();
        }
    }

    fn apply_advice(&mut self, a: Advice) {
        match a {
            Advice::QuickScan => self.start(engine_glue::quick_scan_paths(), "Quick"),
            Advice::Update => self.do_update(),
            Advice::Quarantine => self.view = View::Quarantine,
            Advice::Review => self.view = View::Scan,
        }
    }

    /// Contextual recommendations computed from real state (Bitdefender-style).
    fn recommendations(&self) -> Vec<(String, Option<Advice>)> {
        let mut v = Vec::new();
        let threats = self.last.map(|d| d.malicious + d.suspicious).unwrap_or(0);
        if threats > 0 {
            v.push((
                format!("{threats} detection(s) in your last scan — review and quarantine."),
                Some(Advice::Review),
            ));
        }
        if self.quarantined > 0 {
            v.push((
                format!("{} item(s) waiting in Quarantine.", self.quarantined),
                Some(Advice::Quarantine),
            ));
        }
        if self.last_scan_unix == 0 {
            v.push((
                "You haven't run a scan yet — start with a Quick Scan.".to_string(),
                Some(Advice::QuickScan),
            ));
        }
        if self.last_update_unix == 0 {
            v.push((
                "Update signatures to pull the latest threat intelligence.".to_string(),
                Some(Advice::Update),
            ));
        }
        if v.is_empty() {
            v.push((
                "You're all set — protection is active and definitions are loaded.".to_string(),
                None,
            ));
        }
        v
    }

    fn poll(&mut self, ctx: &egui::Context) {
        let mut finished = false;
        if let Some(rx) = &self.rx {
            loop {
                match rx.try_recv() {
                    Ok(ScanMsg::Progress { scanned, current }) => {
                        self.scanned = scanned;
                        self.current = current;
                    }
                    Ok(ScanMsg::Threat(r)) => {
                        self.scanned += 1;
                        if self.threats.len() < 5000 {
                            self.threats.push(*r);
                        }
                    }
                    Ok(ScanMsg::Done {
                        files,
                        malicious,
                        suspicious,
                        ms,
                        bytes,
                        stopped,
                    }) => {
                        self.last = Some(Done {
                            files,
                            malicious,
                            suspicious,
                            ms,
                            bytes,
                        });
                        self.last_scan_unix = now_unix();
                        self.scanning = false;
                        let outcome = if stopped {
                            "stopped — partial results:"
                        } else {
                            "complete —"
                        };
                        self.status = format!(
                            "{} scan {outcome} {malicious} malicious, {suspicious} suspicious in {files} files",
                            self.scan_label
                        );
                        finished = true;
                    }
                    Ok(ScanMsg::Failed(e)) => {
                        self.scanning = false;
                        self.status = format!("Scan failed: {e}");
                        finished = true;
                    }
                    Err(TryRecvError::Empty) => break,
                    Err(TryRecvError::Disconnected) => {
                        self.scanning = false;
                        finished = true;
                        break;
                    }
                }
            }
        }
        if finished {
            self.rx = None;
            self.scan_stop = None;
            self.refresh_inventory();
            self.activity_loaded = false;
        }

        // Drain a background feed update, if running.
        if let Some(rx) = &self.update_rx {
            match rx.try_recv() {
                Ok(report) => {
                    self.updating = false;
                    self.update_rx = None;
                    self.refresh_inventory();
                    self.sig_source = engine_glue::signatures_source();
                    self.last_update_unix = now_unix();
                    self.activity_loaded = false;
                    let detail = report.messages.join(" · ");
                    self.status = format!(
                        "Update complete — {detail}  →  {} hash signatures, {} YARA files",
                        self.hashes, self.yara
                    );
                }
                Err(TryRecvError::Empty) => {}
                Err(TryRecvError::Disconnected) => {
                    self.updating = false;
                    self.update_rx = None;
                    self.status = "Update failed.".to_string();
                }
            }
        }

        // Drain real-time monitor events (collect first to avoid borrow issues).
        let mut rt_events = Vec::new();
        if let Some(handle) = &self.realtime {
            while let Ok(msg) = handle.rx.try_recv() {
                rt_events.push(msg);
            }
        }
        for msg in rt_events {
            match msg {
                engine_glue::RealtimeMsg::Started(n) => {
                    self.realtime_paths = n;
                    self.status = format!("Real-time monitoring active — watching {n} folder(s).");
                }
                engine_glue::RealtimeMsg::Detection(r) => {
                    self.realtime_hits += 1;
                    self.status = format!("Real-time: detection in {}", r.path);
                    if self.threats.len() < 5000 {
                        self.threats.push(*r);
                    }
                    self.activity_loaded = false;
                }
                engine_glue::RealtimeMsg::Ransomware(path) => {
                    self.realtime_hits += 1;
                    self.status =
                        format!("⚠ RANSOMWARE suspected — canary encrypted/deleted: {path}");
                    self.activity_loaded = false;
                }
                engine_glue::RealtimeMsg::Error(e) => {
                    self.status = format!("Real-time error: {e}");
                    self.realtime = None;
                }
            }
        }

        // Drain a threat-intel lookup, if running.
        let intel_result = self.intel_rx.as_ref().and_then(|rx| rx.try_recv().ok());
        if let Some(result) = intel_result {
            self.intel_busy = false;
            self.intel_rx = None;
            match result {
                Ok(reports) => {
                    let known = reports.iter().filter(|r| r.found).count();
                    self.intel_source =
                        format!("{} provider(s) · {known} with a record", reports.len());
                    let mut lines = Vec::new();
                    for r in reports {
                        lines.push(format!(
                            "── {} · {} ──",
                            r.source,
                            if r.found { "KNOWN" } else { "no record" }
                        ));
                        lines.extend(r.lines);
                    }
                    self.intel_lines = lines;
                }
                Err(e) => {
                    self.intel_source = "Lookup failed".to_string();
                    self.intel_lines = vec![e];
                }
            }
        }

        // Poll the agent service status on a background thread, at most every 2s.
        let nowu = now_unix();
        if self.agent_rx.is_none() && nowu.saturating_sub(self.agent_polled_at) >= 2 {
            self.agent_polled_at = nowu;
            self.agent_rx = Some(agent_link::start_poll());
        }
        if let Some(rx) = &self.agent_rx {
            match rx.try_recv() {
                Ok(status) => {
                    self.agent_status = status;
                    self.agent_rx = None;
                    // The agent owns real-time when present; stop any in-process
                    // watcher so files aren't scanned/quarantined twice.
                    if self.agent_status.is_some() && self.realtime.is_some() {
                        self.stop_realtime();
                    }
                }
                Err(TryRecvError::Empty) => {}
                Err(TryRecvError::Disconnected) => self.agent_rx = None,
            }
        }

        // Poll the agent's activity log while it's present (every ~3s).
        if self.agent_status.is_some()
            && self.agent_events_rx.is_none()
            && nowu.saturating_sub(self.agent_events_polled_at) >= 3
        {
            self.agent_events_polled_at = nowu;
            self.agent_events_rx = Some(agent_link::start_events_poll());
        }
        if let Some(rx) = &self.agent_events_rx {
            match rx.try_recv() {
                Ok(events) => {
                    self.agent_events = events;
                    self.agent_events_rx = None;
                }
                Err(TryRecvError::Empty) => {}
                Err(TryRecvError::Disconnected) => self.agent_events_rx = None,
            }
        }

        // Drain an in-process firewall / web-protection action (no-agent path).
        if let Some(rx) = &self.admin_rx {
            match rx.try_recv() {
                Ok(msg) => {
                    self.admin_busy = false;
                    self.admin_rx = None;
                    match msg {
                        engine_glue::AdminMsg::Firewall { on, blocked, note } => {
                            self.local_fw_on = on;
                            if let Some(b) = blocked {
                                self.local_fw_blocked = b;
                            }
                            self.status = note;
                        }
                        engine_glue::AdminMsg::Web { on, blocked, note } => {
                            self.local_web_on = on;
                            if let Some(b) = blocked {
                                self.local_web_blocked = b;
                            }
                            self.status = note;
                        }
                        engine_glue::AdminMsg::Failed(e) => self.status = e,
                    }
                    self.activity_loaded = false;
                }
                Err(TryRecvError::Empty) => {}
                Err(TryRecvError::Disconnected) => {
                    self.admin_busy = false;
                    self.admin_rx = None;
                }
            }
        }

        if self.scanning
            || self.updating
            || self.realtime.is_some()
            || self.intel_busy
            || self.admin_busy
        {
            ctx.request_repaint();
        } else {
            // Keep the agent-service indicator reasonably fresh while idle.
            ctx.request_repaint_after(std::time::Duration::from_secs(2));
        }
    }
}

impl eframe::App for TalosApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        self.poll(ctx);

        // Upload the bronze-guardian emblem to a texture once.
        if self.hero_tex.is_none() {
            let img = egui::ColorImage::from_rgba_unmultiplied(
                [256, 256],
                include_bytes!("../assets/talos_hero.rgba"),
            );
            self.hero_tex = Some(ctx.load_texture("talos_hero", img, egui::TextureOptions::LINEAR));
        }

        egui::SidePanel::left("nav")
            .exact_width(212.0)
            .resizable(false)
            .frame(egui::Frame::none().fill(BG).inner_margin(16.0))
            .show(ctx, |ui| self.sidebar(ui));

        egui::CentralPanel::default()
            .frame(egui::Frame::none().fill(PANEL).inner_margin(22.0))
            .show(ctx, |ui| {
                egui::ScrollArea::vertical()
                    .auto_shrink([false, false])
                    .show(ui, |ui| match self.view {
                        View::Dashboard => self.dashboard(ui),
                        View::Protection => self.protection(ui),
                        View::Scan => self.scan_view(ui),
                        View::Quarantine => self.quarantine_view(ui),
                        View::Activity => self.activity_view(ui),
                        View::Intel => self.intel_view(ui),
                        View::Settings => self.settings_view(ui),
                        View::About => self.about(ui),
                    });
            });
    }
}

impl TalosApp {
    fn sidebar(&mut self, ui: &mut egui::Ui) {
        ui.add_space(12.0);
        ui.vertical(|ui| {
            ui.label(
                RichText::new("TALOS")
                    .color(ACCENT)
                    .size(22.0)
                    .strong()
                    .extra_letter_spacing(2.0),
            );
            ui.label(
                RichText::new("SYSTEM SECURITY")
                    .color(DIM)
                    .size(10.0)
                    .strong(),
            );
        });
        ui.add_space(24.0);

        nav_section(ui, "SECURITY");
        nav(ui, &mut self.view, View::Dashboard, "Dashboard");
        nav(ui, &mut self.view, View::Protection, "Protection");
        nav(ui, &mut self.view, View::Scan, "Scan");
        ui.add_space(10.0);
        nav_section(ui, "MANAGE");
        nav(ui, &mut self.view, View::Quarantine, "Quarantine");
        nav(ui, &mut self.view, View::Activity, "Activity");
        nav(ui, &mut self.view, View::Intel, "Threat Intel");
        ui.add_space(10.0);
        nav_section(ui, "SYSTEM");
        nav(ui, &mut self.view, View::Settings, "Settings");
        nav(ui, &mut self.view, View::About, "About");

        ui.with_layout(egui::Layout::bottom_up(egui::Align::Min), |ui| {
            ui.add_space(4.0);
            ui.label(
                RichText::new(format!("v{}", self.version))
                    .color(DIM)
                    .size(11.0),
            );
            match &self.tenant {
                Some(t) => ui.label(
                    RichText::new(format!("Managed · {t}"))
                        .color(GREEN)
                        .size(11.0),
                ),
                None => ui.label(RichText::new("Unmanaged (local)").color(DIM).size(11.0)),
            };
        });
    }

    fn dashboard(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Dashboard");

        let threats = self.last.map(|d| d.malicious + d.suspicious).unwrap_or(0);
        let (status_col, title, subtitle) = if self.scanning {
            (AMBER, "Scan in progress", "Talos is inspecting your files…")
        } else if threats > 0 {
            (
                ACCENT,
                "Threats need attention",
                "Review the Scan view and quarantine the findings.",
            )
        } else {
            let sub = if self.realtime.is_some() {
                "Real-time monitoring active · on-demand engine ready"
            } else {
                "On-demand engine ready · enable Real-time in Protection"
            };
            (GREEN, "You're protected", sub)
        };

        // Enterprise status banner: Minimalist and clean.
        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                ui.vertical(|ui| {
                    ui.horizontal(|ui| {
                        ui.label(RichText::new("●").color(status_col).size(20.0));
                        ui.label(
                            RichText::new(title.to_uppercase())
                                .color(TEXT)
                                .size(22.0)
                                .strong()
                                .extra_letter_spacing(1.0),
                        );
                    });
                    ui.add_space(2.0);
                    ui.label(RichText::new(subtitle).color(DIM).size(14.0));
                });
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    let label = if self.scanning {
                        "SCANNING..."
                    } else {
                        "QUICK SCAN"
                    };
                    let btn = egui::Button::new(
                        RichText::new(label)
                            .color(Color32::WHITE)
                            .size(14.0)
                            .strong(),
                    )
                    .fill(ACCENT)
                    .min_size(egui::vec2(160.0, 44.0));
                    if ui.add_enabled(!self.scanning, btn).clicked() {
                        self.start(engine_glue::quick_scan_paths(), "Quick");
                    }
                });
            });
        });

        ui.add_space(12.0);

        // Always-on agent service status (shown when the service is running).
        if let Some(a) = &self.agent_status {
            card(ui, CARD, |ui| {
                ui.horizontal(|ui| {
                    ui.label(RichText::new("●").color(GREEN).size(22.0));
                    ui.add_space(8.0);
                    ui.vertical(|ui| {
                        ui.label(
                            RichText::new("Talos Agent service — ACTIVE")
                                .color(GREEN)
                                .size(15.0)
                                .strong(),
                        );
                        ui.label(
                            RichText::new(format!(
                                "Always-on protection · real-time {} · firewall {} · {} threat(s) blocked · up {}",
                                on_off(a.realtime),
                                on_off(a.firewall),
                                a.threats_blocked,
                                fmt_uptime(a.uptime_secs),
                            ))
                            .color(DIM)
                            .size(12.0),
                        );
                    });
                });
            });
            ui.add_space(12.0);
        }

        // At-a-glance metrics: an even, responsive row of uniform tiles.
        let definitions = (self.hashes + self.yara).to_string();
        let last_scan = if self.last_scan_unix == 0 {
            "never".to_string()
        } else {
            time_ago(self.last_scan_unix)
        };
        let (threats_val, threats_col) = match self.last {
            Some(d) if d.malicious + d.suspicious > 0 => {
                ((d.malicious + d.suspicious).to_string(), ACCENT)
            }
            Some(_) => ("0".to_string(), GREEN),
            None => ("—".to_string(), DIM),
        };
        let quar_col = if self.quarantined > 0 { AMBER } else { TEXT };
        ui.columns(4, |c| {
            stat_tile(
                &mut c[0],
                "Definitions",
                &definitions,
                TEXT,
                "signatures & rules",
            );
            stat_tile(&mut c[1], "Last scan", &last_scan, TEXT, "most recent");
            stat_tile(&mut c[2], "Threats", &threats_val, threats_col, "last scan");
            stat_tile(
                &mut c[3],
                "Quarantine",
                &self.quarantined.to_string(),
                quar_col,
                "isolated",
            );
        });

        ui.add_space(12.0);

        // Security advisor — contextual recommendations.
        let recs = self.recommendations();
        let mut chosen: Option<Advice> = None;
        card(ui, CARD, |ui| {
            ui.label(
                RichText::new("Security advisor")
                    .color(TEXT)
                    .size(16.0)
                    .strong(),
            );
            ui.label(
                RichText::new("Recommended actions for your system.")
                    .color(DIM)
                    .size(12.0),
            );
            ui.add_space(8.0);
            for (text, advice) in &recs {
                ui.horizontal(|ui| {
                    let dot = if advice.is_some() { AMBER } else { GREEN };
                    ui.label(RichText::new("●").color(dot).size(11.0));
                    ui.label(RichText::new(text).color(TEXT).size(13.0));
                    if let Some(a) = advice {
                        ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                            if secondary_button(ui, advice_label(*a)).clicked() {
                                chosen = Some(*a);
                            }
                        });
                    }
                });
            }
        });
        if let Some(a) = chosen {
            self.apply_advice(a);
        }

        ui.add_space(12.0);

        // Definitions + Update.
        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                ui.vertical(|ui| {
                    ui.label(RichText::new("Definitions").color(TEXT).size(16.0).strong());
                    ui.label(
                        RichText::new(format!("Source: {}", self.sig_source))
                            .color(DIM)
                            .size(12.0),
                    );
                    ui.label(
                        RichText::new(format!(
                            "{} hash signatures · {} YARA rule files",
                            self.hashes, self.yara
                        ))
                        .color(DIM)
                        .size(12.0),
                    );
                    let updated = if self.last_update_unix == 0 {
                        "not checked this session".to_string()
                    } else {
                        time_ago(self.last_update_unix)
                    };
                    ui.label(
                        RichText::new(format!("Last updated: {updated}"))
                            .color(DIM)
                            .size(12.0),
                    );
                });
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    let label = if self.updating {
                        "Updating…"
                    } else {
                        "Update"
                    };
                    let btn =
                        egui::Button::new(RichText::new(label).color(Color32::WHITE).strong())
                            .fill(ACCENT)
                            .min_size(egui::vec2(150.0, 38.0));
                    if ui.add_enabled(!self.updating, btn).clicked() {
                        self.do_update();
                    }
                });
            });
            ui.add_space(4.0);
            ui.label(
                RichText::new(
                    "Fetches openly-licensed feeds (abuse.ch hashes + open YARA rules) into \
                     your local store and reloads the engine. Signed delta channel is on the roadmap.",
                )
                .color(DIM)
                .size(11.0),
            );
        });

        ui.add_space(10.0);
        ui.label(RichText::new(&self.status).color(DIM).size(12.0));
    }

    fn protection(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Protection");
        ui.label(
            RichText::new(
                "Layered on-demand protection. Real-time modules arrive with the Phase-2 \
                 kernel sensor (see docs/01).",
            )
            .color(DIM)
            .size(12.0),
        );
        ui.add_space(10.0);

        nav_section(ui, "ACTIVE");

        // Always-on agent service (the installed Windows Service / `talos-agent`).
        match &self.agent_status {
            Some(a) => {
                let desc = format!(
                    "Running as a background service — protects at boot, even when this window is \
                     closed. Real-time {}, firewall {}, {} threat(s) blocked, up {}.",
                    on_off(a.realtime),
                    on_off(a.firewall),
                    a.threats_blocked,
                    fmt_uptime(a.uptime_secs),
                );
                module_card(ui, "Agent Service (always-on)", &desc, ModuleStatus::Active);
            }
            None => {
                card(ui, CARD, |ui| {
                    ui.horizontal(|ui| {
                        ui.vertical(|ui| {
                            ui.label(
                                RichText::new("Agent Service (always-on)")
                                    .color(TEXT)
                                    .size(15.0)
                                    .strong(),
                            );
                            ui.label(
                                RichText::new(
                                    "Not detected. Install the MSI (or run `talos-agent install`) to \
                                     protect at boot — real-time, ransomware guard and firewall keep \
                                     running when this app is closed.",
                                )
                                .color(DIM)
                                .size(12.0),
                            );
                        });
                        ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                            ui.label(
                                RichText::new("● NOT INSTALLED")
                                    .color(AMBER)
                                    .size(12.0)
                                    .strong(),
                            );
                        });
                    });
                });
                ui.add_space(8.0);
            }
        }

        // Real-time on-access monitoring. When the agent service is running it
        // owns real-time, so the toggle drives the service over IPC (no
        // double-watching); otherwise the GUI runs its own in-process watcher.
        let agent_realtime = self.agent_status.as_ref().map(|a| a.realtime);
        if let Some(on_now) = agent_realtime {
            let mut on = on_now;
            let desc = "Handled by the always-on agent service — on-access scan + \
                        auto-quarantine across the high-risk folders. Toggling controls the \
                        service (it keeps protecting even when this window is closed)."
                .to_string();
            if module_toggle(ui, "Real-time Protection", &desc, &mut on) {
                agent_link::set_realtime(on);
                self.status = format!(
                    "Real-time {} via the agent service.",
                    if on { "enabled" } else { "disabled" }
                );
            }
        } else {
            let mut rt_on = self.realtime.is_some();
            let rt_desc = if self.realtime.is_some() {
                format!(
                    "ACTIVE — on-access scan + auto-quarantine · {} folder(s) · {} hit(s)",
                    self.realtime_paths, self.realtime_hits
                )
            } else {
                "On-access scan + instant auto-quarantine of new/changed files. Pre-execution \
                 blocking = Phase-2 minifilter (Windows) or `talos watch --enforce` (Linux/fanotify)."
                    .to_string()
            };
            if module_toggle(ui, "Real-time Protection", &rt_desc, &mut rt_on) {
                if rt_on {
                    self.start_realtime();
                } else {
                    self.stop_realtime();
                }
            }
        }

        module_card(
            ui,
            "Antimalware Engine",
            &format!(
                "Exact SHA-256 hash signatures for known-bad files · {} loaded.",
                self.hashes
            ),
            ModuleStatus::Active,
        );
        module_card(
            ui,
            "YARA Rules",
            &format!(
                "Pattern matching: web shells, malicious PowerShell, offensive tooling · {} rule file(s).",
                self.yara
            ),
            ModuleStatus::Active,
        );

        // Real toggles wired to settings (persisted + applied on next scan).
        let mut h = self.config.heuristics;
        if module_toggle(
            ui,
            "Heuristic Analysis",
            "Static PE checks: packing, process-injection imports, W^X sections.",
            &mut h,
        ) {
            self.config.heuristics = h;
            self.config.save();
        }
        let mut b = self.config.behavior;
        if module_toggle(
            ui,
            "Behavioral Analysis",
            "CAPA-style capability inference from imports & strings, MITRE ATT&CK-tagged.",
            &mut b,
        ) {
            self.config.behavior = b;
            self.config.save();
        }
        let mut a = self.config.scan_archives;
        if module_toggle(
            ui,
            "Archive Inspection",
            "Look inside ZIP archives (zip-bomb-guarded).",
            &mut a,
        ) {
            self.config.scan_archives = a;
            self.config.save();
        }

        module_card(
            ui,
            "Quarantine Vault",
            &format!(
                "Isolate detected files and restore false positives · {} item(s) in the vault.",
                self.quarantined
            ),
            ModuleStatus::Active,
        );
        module_card(
            ui,
            "Signature Updates",
            &format!(
                "abuse.ch malware hashes + open YARA feeds, on demand · {} signatures loaded.",
                self.hashes
            ),
            ModuleStatus::Active,
        );
        let rguard_desc = if self.agent_status.is_some() {
            "Canary decoys detect mass-encryption in real time — always-on via the agent service."
        } else if self.realtime.is_some() {
            "Canary decoys detect mass-encryption in real time — active with Real-time."
        } else {
            "Canary decoys detect mass-encryption in real time (activates with Real-time or the agent)."
        };
        module_card(ui, "Ransomware Guard", rguard_desc, ModuleStatus::Active);
        module_card(
            ui,
            "Pre-execution Blocking",
            "Blocks malicious open/exec on Linux via fanotify (`talos watch --enforce`). \
             Windows kernel minifilter = Phase 2.",
            ModuleStatus::Active,
        );
        // Firewall (C2 blocking). With the privileged agent present, controls
        // route to it over IPC; otherwise the GUI applies rules in-process
        // (works when the app runs elevated — noted inline for the user).
        let agent_fw = self
            .agent_status
            .as_ref()
            .map(|a| (a.firewall, a.firewall_blocked));
        let (fw_on, fw_blocked, fw_agent) = match agent_fw {
            Some((on, n)) => (on, n, true),
            None => (self.local_fw_on, self.local_fw_blocked, false),
        };
        let busy = self.admin_busy;
        let mut toggle_fw: Option<bool> = None;
        let mut block_now = false;
        let mut unblock_now = false;
        let mut flush_now = false;
        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                ui.vertical(|ui| {
                    ui.label(
                        RichText::new("Firewall (C2 blocking)")
                            .color(TEXT)
                            .size(15.0)
                            .strong(),
                    );
                    let desc = if fw_agent {
                        format!(
                            "Blocks outbound C2 traffic via the OS firewall · {fw_blocked} IP(s) \
                             blocked. Sync the abuse.ch list or block your own below."
                        )
                    } else {
                        format!(
                            "Blocks outbound C2 traffic via the OS firewall · {fw_blocked} IP(s) \
                             blocked. Applied directly by this app — needs Administrator/root (or \
                             install the agent to run it always-on)."
                        )
                    };
                    ui.label(RichText::new(desc).color(DIM).size(12.0));
                });
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    let mut on = fw_on;
                    let label = if busy {
                        "…"
                    } else if on {
                        "On"
                    } else {
                        "Off"
                    };
                    ui.add_enabled_ui(!busy, |ui| {
                        if ui.toggle_value(&mut on, label).changed() {
                            toggle_fw = Some(on);
                        }
                    });
                });
            });
            ui.add_space(6.0);
            ui.add_enabled_ui(!busy, |ui| {
                ui.horizontal(|ui| {
                    ui.label(RichText::new("Block IP:").color(DIM).size(12.0));
                    ui.add(
                        egui::TextEdit::singleline(&mut self.firewall_ip)
                            .desired_width(170.0)
                            .hint_text("203.0.113.7"),
                    );
                    if secondary_button(ui, "Block").clicked() {
                        block_now = true;
                    }
                    if secondary_button(ui, "Unblock").clicked() {
                        unblock_now = true;
                    }
                    if secondary_button(ui, "Flush all").clicked() {
                        flush_now = true;
                    }
                });
            });
        });
        ui.add_space(8.0);
        // Apply firewall actions outside the egui closures (no nested &mut self).
        if let Some(on) = toggle_fw {
            if fw_agent {
                agent_link::set_firewall(on);
                self.status = format!(
                    "C2 blocklist {} via the agent service.",
                    if on { "syncing" } else { "flushed" }
                );
            } else if !self.admin_busy {
                self.admin_busy = true;
                self.admin_rx = Some(if on {
                    engine_glue::start_firewall_sync()
                } else {
                    engine_glue::start_firewall_flush()
                });
                self.status = if on {
                    "Syncing C2 blocklist into the firewall…".to_string()
                } else {
                    "Removing Talos firewall rules…".to_string()
                };
            }
        }
        if block_now {
            let ip = self.firewall_ip.trim().to_string();
            if ip.is_empty() {
                self.status = "Enter an IPv4 address to block.".to_string();
            } else if fw_agent {
                agent_link::block_ip(ip);
                self.firewall_ip.clear();
                self.status = "Requested outbound IP block via the agent.".to_string();
            } else if !self.admin_busy {
                self.admin_busy = true;
                self.admin_rx = Some(engine_glue::start_firewall_block(ip));
                self.firewall_ip.clear();
                self.status = "Blocking outbound IP…".to_string();
            }
        }
        if unblock_now {
            let ip = self.firewall_ip.trim().to_string();
            if ip.is_empty() {
                self.status = "Enter an IPv4 address to unblock.".to_string();
            } else if fw_agent {
                agent_link::unblock_ip(ip);
                self.firewall_ip.clear();
                self.status = "Requested outbound IP unblock via the agent.".to_string();
            } else if !self.admin_busy {
                self.admin_busy = true;
                self.admin_rx = Some(engine_glue::start_firewall_unblock(ip));
                self.firewall_ip.clear();
                self.status = "Unblocking IP…".to_string();
            }
        }
        if flush_now {
            if fw_agent {
                agent_link::set_firewall(false);
                self.status = "Removing all Talos firewall rules…".to_string();
            } else if !self.admin_busy {
                self.admin_busy = true;
                self.admin_rx = Some(engine_glue::start_firewall_flush());
                self.status = "Removing all Talos firewall rules…".to_string();
            }
        }

        // Web / domain protection. Agent present → control over IPC; otherwise
        // the GUI applies the hosts-file sinkhole in-process (needs elevation).
        let agent_web = self
            .agent_status
            .as_ref()
            .map(|a| (a.web_protection, a.web_blocked));
        let (web_on, web_blocked, web_agent) = match agent_web {
            Some((on, n)) => (on, n, true),
            None => (self.local_web_on, self.local_web_blocked, false),
        };
        let busy = self.admin_busy;
        let mut toggle_web: Option<bool> = None;
        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                ui.vertical(|ui| {
                    ui.label(
                        RichText::new("Web Protection (malicious domains)")
                            .color(TEXT)
                            .size(15.0)
                            .strong(),
                    );
                    let desc = if web_agent {
                        format!(
                            "Sinkholes known-malicious domains (abuse.ch URLhaus) at the OS \
                             resolver · {web_blocked} domain(s) blocked."
                        )
                    } else {
                        format!(
                            "Sinkholes known-malicious domains (abuse.ch URLhaus) via the hosts \
                             file · {web_blocked} domain(s) blocked. Applied directly by this app — \
                             needs Administrator/root (or install the agent)."
                        )
                    };
                    ui.label(RichText::new(desc).color(DIM).size(12.0));
                });
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    let mut on = web_on;
                    let label = if busy {
                        "…"
                    } else if on {
                        "On"
                    } else {
                        "Off"
                    };
                    ui.add_enabled_ui(!busy, |ui| {
                        if ui.toggle_value(&mut on, label).changed() {
                            toggle_web = Some(on);
                        }
                    });
                });
            });
        });
        ui.add_space(8.0);
        if let Some(on) = toggle_web {
            if web_agent {
                agent_link::set_web_protection(on);
                self.status = format!(
                    "Web protection {} via the agent service.",
                    if on { "syncing" } else { "cleared" }
                );
            } else if !self.admin_busy {
                self.admin_busy = true;
                self.admin_rx = Some(if on {
                    engine_glue::start_web_sync()
                } else {
                    engine_glue::start_web_clear()
                });
                self.status = if on {
                    "Syncing URLhaus blocklist into the hosts file…".to_string()
                } else {
                    "Clearing web protection…".to_string()
                };
            }
        }

        // ─── Custom Rules ──────────────────────────────────────────────────
        ui.add_space(12.0);
        nav_section(ui, "CUSTOM RULES");

        // Predefined baseline display (read-only).
        card(ui, CARD, |ui| {
            ui.label(
                RichText::new("Predefined Baseline Blocks")
                    .color(TEXT)
                    .size(15.0)
                    .strong(),
            );
            ui.label(
                RichText::new(
                    "Applied at every agent start — no network required. Covers RAT/C2/Tor/mining \
                     endpoints with no legitimate use on managed endpoints.",
                )
                .color(DIM)
                .size(12.0),
            );
            ui.add_space(8.0);
            ui.label(
                RichText::new("BLOCKED PORTS")
                    .color(DIM)
                    .size(10.5)
                    .strong(),
            );
            ui.add_space(4.0);
            let midpoint = BASELINE_PORTS.len().div_ceil(2);
            ui.columns(2, |cols| {
                for (i, (port, _)) in BASELINE_PORTS.iter().enumerate() {
                    let col = if i < midpoint { 0 } else { 1 };
                    cols[col].horizontal(|ui| {
                        ui.label(
                            RichText::new(format!("TCP/{port}"))
                                .color(ACCENT)
                                .size(12.0)
                                .strong(),
                        );
                        ui.label(RichText::new(port_label(*port)).color(DIM).size(11.0));
                    });
                }
            });
            ui.add_space(8.0);
            ui.label(RichText::new("BLOCKED IPs").color(DIM).size(10.5).strong());
            ui.add_space(4.0);
            for (ip, label) in BASELINE_BLOCKS {
                ui.horizontal(|ui| {
                    ui.label(RichText::new(*ip).color(ACCENT).size(12.0).strong());
                    ui.label(RichText::new(*label).color(DIM).size(11.0));
                });
            }
        });
        ui.add_space(8.0);

        let busy = self.admin_busy;

        // Custom port rules.
        let mut add_port: Option<u16> = None;
        let mut remove_port_idx: Option<usize> = None;
        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                ui.label(
                    RichText::new("Custom Port Blocks")
                        .color(TEXT)
                        .size(15.0)
                        .strong(),
                );
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    ui.label(
                        RichText::new(format!(
                            "{} rule(s)",
                            self.config.custom_blocked_ports.len()
                        ))
                        .color(DIM)
                        .size(12.0),
                    );
                });
            });
            ui.label(
                RichText::new(
                    "Drop outbound TCP connections to additional ports. \
                     Requires Administrator/root.",
                )
                .color(DIM)
                .size(12.0),
            );
            ui.add_space(8.0);
            ui.add_enabled_ui(!busy, |ui| {
                ui.horizontal(|ui| {
                    ui.label(RichText::new("TCP port:").color(DIM).size(12.0));
                    ui.add(
                        egui::TextEdit::singleline(&mut self.new_port_rule)
                            .desired_width(80.0)
                            .hint_text("8080"),
                    );
                    if secondary_button(ui, "Add").clicked() {
                        if let Ok(p) = self.new_port_rule.trim().parse::<u16>() {
                            if p > 0 {
                                add_port = Some(p);
                            }
                        }
                    }
                });
            });
            ui.add_space(6.0);
            if self.config.custom_blocked_ports.is_empty() {
                ui.label(RichText::new("No custom port rules.").color(DIM).size(12.0));
            } else {
                let ports: Vec<u16> = self.config.custom_blocked_ports.clone();
                for (i, port) in ports.iter().enumerate() {
                    ui.horizontal(|ui| {
                        ui.label(
                            RichText::new(format!("TCP/{port}"))
                                .color(TEXT)
                                .size(13.0)
                                .strong(),
                        );
                        ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                            ui.add_enabled_ui(!busy, |ui| {
                                if ui
                                    .small_button(RichText::new("Remove").color(ACCENT).size(11.0))
                                    .clicked()
                                {
                                    remove_port_idx = Some(i);
                                }
                            });
                        });
                    });
                }
            }
        });
        ui.add_space(8.0);

        if let Some(port) = add_port {
            let in_baseline = BASELINE_PORTS.iter().any(|(p, _)| *p == port);
            if in_baseline {
                self.new_port_rule.clear();
                self.status = format!("TCP/{port} is already in the predefined baseline.");
            } else if self.config.custom_blocked_ports.contains(&port) {
                self.new_port_rule.clear();
                self.status = format!("TCP/{port} is already in the custom block list.");
            } else {
                self.config.custom_blocked_ports.push(port);
                self.config.save();
                self.new_port_rule.clear();
                if !self.admin_busy {
                    self.admin_busy = true;
                    self.admin_rx = Some(engine_glue::start_firewall_block_port(port));
                    self.status = format!("Blocking outbound TCP/{port}…");
                }
            }
        }
        if let Some(i) = remove_port_idx {
            let port = self.config.custom_blocked_ports[i];
            self.config.custom_blocked_ports.remove(i);
            self.config.save();
            if !self.admin_busy {
                self.admin_busy = true;
                self.admin_rx = Some(engine_glue::start_firewall_unblock_port(port));
                self.status = format!("Removing TCP/{port} block…");
            }
        }

        // Custom IP / CIDR rules.
        let mut add_ip: Option<String> = None;
        let mut remove_ip_idx: Option<usize> = None;
        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                ui.label(
                    RichText::new("Custom IP / CIDR Blocks")
                        .color(TEXT)
                        .size(15.0)
                        .strong(),
                );
                ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                    ui.label(
                        RichText::new(format!("{} rule(s)", self.config.custom_blocked_ips.len()))
                            .color(DIM)
                            .size(12.0),
                    );
                });
            });
            ui.label(
                RichText::new(
                    "Drop outbound traffic to a specific IPv4 address or subnet. \
                     Accepts bare IPs (1.2.3.4) and CIDR notation (1.2.3.0/24).",
                )
                .color(DIM)
                .size(12.0),
            );
            ui.add_space(8.0);
            ui.add_enabled_ui(!busy, |ui| {
                ui.horizontal(|ui| {
                    ui.label(RichText::new("IP / CIDR:").color(DIM).size(12.0));
                    ui.add(
                        egui::TextEdit::singleline(&mut self.new_ip_rule)
                            .desired_width(180.0)
                            .hint_text("203.0.113.7  or  198.51.100.0/24"),
                    );
                    if secondary_button(ui, "Add").clicked() {
                        let ip = self.new_ip_rule.trim().to_string();
                        if !ip.is_empty() {
                            add_ip = Some(ip);
                        }
                    }
                });
            });
            ui.add_space(6.0);
            if self.config.custom_blocked_ips.is_empty() {
                ui.label(RichText::new("No custom IP rules.").color(DIM).size(12.0));
            } else {
                let ips: Vec<String> = self.config.custom_blocked_ips.clone();
                for (i, ip) in ips.iter().enumerate() {
                    ui.horizontal(|ui| {
                        ui.label(RichText::new(ip.as_str()).color(TEXT).size(13.0).strong());
                        ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                            ui.add_enabled_ui(!busy, |ui| {
                                if ui
                                    .small_button(RichText::new("Remove").color(ACCENT).size(11.0))
                                    .clicked()
                                {
                                    remove_ip_idx = Some(i);
                                }
                            });
                        });
                    });
                }
            }
        });
        ui.add_space(8.0);

        if let Some(ip) = add_ip {
            if self.config.custom_blocked_ips.contains(&ip) {
                self.new_ip_rule.clear();
                self.status = format!("{ip} is already in the block list.");
            } else {
                self.config.custom_blocked_ips.push(ip.clone());
                self.config.save();
                self.new_ip_rule.clear();
                if fw_agent {
                    agent_link::block_ip(ip.clone());
                    self.status = format!("Blocking {ip} via agent service.");
                } else if !self.admin_busy {
                    self.admin_busy = true;
                    self.admin_rx = Some(engine_glue::start_firewall_block(ip.clone()));
                    self.status = format!("Blocking outbound {ip}…");
                }
            }
        }
        if let Some(i) = remove_ip_idx {
            let ip = self.config.custom_blocked_ips[i].clone();
            self.config.custom_blocked_ips.remove(i);
            self.config.save();
            if fw_agent {
                agent_link::unblock_ip(ip.clone());
                self.status = format!("Removed {ip} block via agent service.");
            } else if !self.admin_busy {
                self.admin_busy = true;
                self.admin_rx = Some(engine_glue::start_firewall_unblock(ip.clone()));
                self.status = format!("Removing {ip} block…");
            }
        }

        ui.add_space(12.0);
        nav_section(ui, "ROADMAP · PHASE 2 (KERNEL SENSOR)");
        for (name, desc) in [
            (
                "Pre-execution Blocking (Windows)",
                "Kernel file-system minifilter + AMSI to block before run.",
            ),
            (
                "Web Protection — in-browser URL filtering",
                "Per-URL inspection + phishing block (domain-level blocking is Active above).",
            ),
            (
                "Ransomware Rollback",
                "Kernel I/O filter + Volume Shadow Copy to restore encrypted files.",
            ),
            (
                "Banking & Payment",
                "Hardened isolated browser for transactions.",
            ),
        ] {
            module_card(ui, name, desc, ModuleStatus::Roadmap);
        }
    }

    fn scan_view(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Scan");

        ui.add_enabled_ui(!self.scanning, |ui| {
            ui.horizontal(|ui| {
                if primary_button(ui, "Quick Scan").clicked() {
                    self.start(engine_glue::quick_scan_paths(), "Quick");
                }
                if secondary_button(ui, "Full Scan").clicked() {
                    self.start(engine_glue::full_scan_roots(), "Full");
                }
            });
            ui.add_space(8.0);
            ui.horizontal(|ui| {
                ui.label(RichText::new("Custom path:").color(DIM));
                ui.add(
                    egui::TextEdit::singleline(&mut self.custom_path)
                        .desired_width(420.0)
                        .hint_text("C:\\Users\\me\\Downloads"),
                );
                if secondary_button(ui, "Scan").clicked() {
                    let trimmed = self.custom_path.trim().to_string();
                    let p = PathBuf::from(&trimmed);
                    if trimmed.is_empty() {
                        self.status = "Enter a path to scan.".to_string();
                    } else if !p.exists() {
                        self.status = format!("Path does not exist: {trimmed}");
                    } else {
                        self.start(vec![p], "Custom");
                    }
                }
            });
        });

        ui.add_space(10.0);
        let mut stop_clicked = false;
        card(ui, CARD, |ui| {
            if self.scanning {
                ui.horizontal(|ui| {
                    ui.add(egui::Spinner::new().color(ACCENT));
                    ui.label(
                        RichText::new(format!(
                            "Scanning… {} files · {} threats",
                            self.scanned,
                            self.threats.len()
                        ))
                        .color(TEXT)
                        .size(15.0),
                    );
                    ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                        if secondary_button(ui, "Stop").clicked() {
                            stop_clicked = true;
                        }
                    });
                });
                ui.label(
                    RichText::new(truncate(&self.current, 80))
                        .color(DIM)
                        .size(11.0),
                );
            } else if let Some(d) = self.last {
                let mibps = if d.ms > 0 {
                    (d.bytes as f64 / 1_048_576.0) / (d.ms as f64 / 1000.0)
                } else {
                    0.0
                };
                ui.label(
                    RichText::new(format!(
                        "{} scan: {} files · {} malicious · {} suspicious · {} ms · {:.1} MiB/s",
                        self.scan_label, d.files, d.malicious, d.suspicious, d.ms, mibps
                    ))
                    .color(TEXT),
                );
            } else {
                ui.label(RichText::new("Choose a scan to begin.").color(DIM));
            }
        });
        if stop_clicked {
            self.stop_scan();
        }

        if !self.threats.is_empty() {
            ui.add_space(8.0);
            let malicious = self.threats.iter().filter(|r| r.is_malicious()).count();
            let mut do_quarantine = false;
            ui.horizontal(|ui| {
                ui.label(
                    RichText::new(format!("Detections ({})", self.threats.len()))
                        .color(TEXT)
                        .strong(),
                );
                if malicious > 0
                    && !self.scanning
                    && secondary_button(ui, &format!("Quarantine {malicious}")).clicked()
                {
                    do_quarantine = true;
                }
            });
            if do_quarantine {
                match engine_glue::quarantine_reports(&self.threats) {
                    Ok(n) => {
                        self.status = format!("Quarantined {n} item(s).");
                        history::record("quarantine", format!("Quarantined {n} item(s)"));
                        self.threats.retain(|r| !r.is_malicious());
                        self.q_loaded = false;
                        self.activity_loaded = false;
                        self.refresh_inventory();
                    }
                    Err(e) => self.status = format!("Quarantine failed: {e}"),
                }
            }

            egui::ScrollArea::vertical()
                .auto_shrink([false, false])
                .show(ui, |ui| {
                    for r in &self.threats {
                        for d in &r.detections {
                            ui.horizontal(|ui| {
                                ui.label(
                                    RichText::new(sev_tag(d.severity))
                                        .color(sev_color(d.severity))
                                        .strong(),
                                );
                                ui.label(RichText::new(&r.path).color(TEXT).size(12.0));
                                ui.label(
                                    RichText::new(format!("→ {}", d.name)).color(DIM).size(12.0),
                                );
                            });
                        }
                    }
                });
        }
    }

    fn quarantine_view(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Quarantine");
        if !self.q_loaded {
            self.reload_quarantine();
        }
        ui.horizontal(|ui| {
            if secondary_button(ui, "Refresh").clicked() {
                self.reload_quarantine();
            }
            ui.label(RichText::new(format!("{} item(s)", self.q_items.len())).color(DIM));
        });
        ui.add_space(6.0);

        if self.q_items.is_empty() {
            card(ui, CARD, |ui| {
                ui.label(RichText::new("Quarantine is empty.").color(DIM));
            });
            return;
        }

        enum Act {
            Restore,
            Purge,
        }
        let mut action: Option<(Act, String)> = None;

        egui::ScrollArea::vertical()
            .auto_shrink([false, false])
            .show(ui, |ui| {
                for item in &self.q_items {
                    card(ui, CARD, |ui| {
                        ui.horizontal(|ui| {
                            ui.vertical(|ui| {
                                ui.label(RichText::new(&item.original_path).color(TEXT).size(12.0));
                                let names: Vec<&str> =
                                    item.detections.iter().map(|d| d.name.as_str()).collect();
                                ui.label(RichText::new(names.join(", ")).color(DIM).size(11.0));
                            });
                            ui.with_layout(
                                egui::Layout::right_to_left(egui::Align::Center),
                                |ui| {
                                    if ui.button(RichText::new("Delete").color(ACCENT)).clicked() {
                                        action = Some((Act::Purge, item.id.clone()));
                                    }
                                    if ui.button("Restore").clicked() {
                                        action = Some((Act::Restore, item.id.clone()));
                                    }
                                },
                            );
                        });
                    });
                }
            });

        if let Some((act, id)) = action {
            if let Ok(store) = scanner_core::Quarantine::open(engine_glue::quarantine_dir()) {
                let _ = match act {
                    Act::Restore => {
                        history::record("quarantine", "Restored an item from quarantine");
                        store.restore(&id, None).map(|_| ())
                    }
                    Act::Purge => {
                        history::record("quarantine", "Deleted an item from quarantine");
                        store.purge(&id)
                    }
                };
            }
            self.status = "Quarantine updated.".to_string();
            self.activity_loaded = false;
            self.reload_quarantine();
            self.refresh_inventory();
        }
    }

    fn activity_view(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Activity");
        if !self.activity_loaded {
            self.reload_activity();
        }
        ui.horizontal(|ui| {
            if secondary_button(ui, "Refresh").clicked() {
                self.reload_activity();
            }
            let total = self.activity.len() + self.agent_events.len();
            ui.label(RichText::new(format!("{total} event(s)")).color(DIM));
        });
        ui.add_space(6.0);

        if self.activity.is_empty() && self.agent_events.is_empty() {
            card(ui, CARD, |ui| {
                ui.label(
                    RichText::new(
                        "No activity yet. Run a scan, or install the agent for live \
                         protection events.",
                    )
                    .color(DIM),
                );
            });
            return;
        }

        egui::ScrollArea::vertical()
            .auto_shrink([false, false])
            .show(ui, |ui| {
                // Live protection events streamed from the agent service (newest first).
                if !self.agent_events.is_empty() {
                    ui.label(
                        RichText::new("LIVE PROTECTION · AGENT SERVICE")
                            .color(DIM)
                            .size(10.5)
                            .strong(),
                    );
                    ui.add_space(2.0);
                    for e in self.agent_events.iter().rev() {
                        card(ui, CARD, |ui| {
                            ui.horizontal(|ui| {
                                let col = match e.severity.as_str() {
                                    "threat" | "ransomware" => ACCENT,
                                    "blocked" => GREEN,
                                    "error" => AMBER,
                                    _ => DIM,
                                };
                                ui.label(RichText::new("●").color(col).size(13.0));
                                ui.add_space(4.0);
                                ui.vertical(|ui| {
                                    ui.label(RichText::new(&e.message).color(TEXT).size(12.0));
                                    let when = time_ago(e.unix);
                                    let sub = match &e.path {
                                        Some(p) => format!("{when} · {p}"),
                                        None => when,
                                    };
                                    ui.label(RichText::new(sub).color(DIM).size(11.0));
                                });
                            });
                        });
                    }
                    ui.add_space(8.0);
                }

                if !self.activity.is_empty() {
                    ui.label(
                        RichText::new("LOCAL ACTIVITY")
                            .color(DIM)
                            .size(10.5)
                            .strong(),
                    );
                    ui.add_space(2.0);
                    for e in &self.activity {
                        card(ui, CARD, |ui| {
                            ui.horizontal(|ui| {
                                let col = match e.kind.as_str() {
                                    "scan" => GREEN,
                                    "update" => AMBER,
                                    "quarantine" => ACCENT,
                                    _ => DIM,
                                };
                                ui.label(RichText::new("●").color(col).size(13.0));
                                ui.add_space(4.0);
                                ui.vertical(|ui| {
                                    ui.label(RichText::new(&e.summary).color(TEXT).size(12.0));
                                    ui.label(RichText::new(time_ago(e.unix)).color(DIM).size(11.0));
                                });
                            });
                        });
                    }
                }
            });
    }

    fn intel_view(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Threat Intelligence");
        ui.label(
            RichText::new(
                "Look up a file's SHA-256 against a free online malware database. Only the \
                 hash is sent — never file contents.",
            )
            .color(DIM)
            .size(12.0),
        );
        ui.add_space(10.0);

        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                ui.add(
                    egui::TextEdit::singleline(&mut self.intel_query)
                        .desired_width(520.0)
                        .hint_text("SHA-256 hash (64 hex characters)"),
                );
                let label = if self.intel_busy {
                    "Looking up…"
                } else {
                    "Look up"
                };
                if ui
                    .add_enabled(
                        !self.intel_busy,
                        egui::Button::new(RichText::new(label).color(Color32::WHITE).strong())
                            .fill(ACCENT)
                            .min_size(egui::vec2(120.0, 32.0)),
                    )
                    .clicked()
                {
                    self.do_intel();
                }
            });
            ui.add_space(4.0);
            ui.label(
                RichText::new(
                    "Queries every provider you have a key for: TALOS_VT_KEY (VirusTotal), \
                     TALOS_ABUSE_KEY (MalwareBazaar), TALOS_MALSHARE_KEY, TALOS_OTX_KEY \
                     (AlienVault), TALOS_HYBRID_KEY (Hybrid Analysis).",
                )
                .color(DIM)
                .size(11.0),
            );
        });

        if !self.intel_lines.is_empty() {
            ui.add_space(10.0);
            card(ui, CARD, |ui| {
                ui.label(
                    RichText::new(format!("Source: {}", self.intel_source))
                        .color(TEXT)
                        .strong(),
                );
                ui.add_space(4.0);
                for line in &self.intel_lines {
                    ui.label(RichText::new(line).color(DIM).size(12.0));
                }
            });
        }
    }

    fn settings_view(&mut self, ui: &mut egui::Ui) {
        heading(ui, "Settings");
        let mut dirty = false;

        // --- Scan engine ---
        card(ui, CARD, |ui| {
            ui.label(RichText::new("Scan engine").color(TEXT).size(16.0).strong());
            ui.add_space(6.0);
            if ui
                .add(
                    egui::Slider::new(&mut self.config.max_size_mib, 1..=1024)
                        .text("Max file size for content/YARA scan (MiB)"),
                )
                .changed()
            {
                dirty = true;
            }
            if ui
                .checkbox(
                    &mut self.config.scan_archives,
                    "Inspect inside ZIP archives",
                )
                .changed()
            {
                dirty = true;
            }
            if ui
                .checkbox(
                    &mut self.config.heuristics,
                    "Static PE heuristics (packing / injection / W^X)",
                )
                .changed()
            {
                dirty = true;
            }
            if ui
                .checkbox(
                    &mut self.config.behavior,
                    "Behavioral analysis (capability inference, MITRE ATT&CK)",
                )
                .changed()
            {
                dirty = true;
            }
            if ui
                .checkbox(&mut self.config.follow_symlinks, "Follow symbolic links")
                .changed()
            {
                dirty = true;
            }
        });
        ui.add_space(10.0);

        // --- Exclusions ---
        card(ui, CARD, |ui| {
            ui.label(RichText::new("Exclusions").color(TEXT).size(16.0).strong());
            ui.label(
                RichText::new("Trusted files or folders to skip during scans.")
                    .color(DIM)
                    .size(12.0),
            );
            ui.add_space(6.0);
            ui.horizontal(|ui| {
                ui.add(
                    egui::TextEdit::singleline(&mut self.new_exclusion)
                        .desired_width(420.0)
                        .hint_text("C:\\path\\to\\trusted  (file or folder)"),
                );
                if secondary_button(ui, "Add").clicked() {
                    let p = self.new_exclusion.trim().to_string();
                    if !p.is_empty() && !self.config.exclusions.contains(&p) {
                        self.config.exclusions.push(p);
                        self.new_exclusion.clear();
                        dirty = true;
                    }
                }
            });
            ui.add_space(4.0);
            let mut remove: Option<usize> = None;
            for (i, ex) in self.config.exclusions.iter().enumerate() {
                ui.horizontal(|ui| {
                    ui.label(RichText::new(ex).color(TEXT).size(12.0));
                    ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                        if ui.button("Remove").clicked() {
                            remove = Some(i);
                        }
                    });
                });
            }
            if let Some(i) = remove {
                self.config.exclusions.remove(i);
                dirty = true;
            }
            if self.config.exclusions.is_empty() {
                ui.label(
                    RichText::new("No exclusions configured.")
                        .color(DIM)
                        .size(12.0),
                );
            }
        });
        ui.add_space(10.0);

        // --- Startup protection ---
        card(ui, CARD, |ui| {
            ui.label(
                RichText::new("Startup protection")
                    .color(TEXT)
                    .size(16.0)
                    .strong(),
            );
            ui.label(
                RichText::new(
                    "Bring network defenses up automatically when the agent service starts.",
                )
                .color(DIM)
                .size(11.0),
            );
            ui.add_space(6.0);
            if ui
                .checkbox(
                    &mut self.config.firewall_autostart,
                    "Firewall — block malware ports, RAT/Tor IPs, and C2 feeds at boot",
                )
                .changed()
            {
                dirty = true;
            }
            if ui
                .checkbox(
                    &mut self.config.web_autostart,
                    "Web protection — sinkhole known-malicious domains at boot",
                )
                .changed()
            {
                dirty = true;
            }
        });
        ui.add_space(10.0);

        // --- Scheduled scan ---
        card(ui, CARD, |ui| {
            ui.label(
                RichText::new("Scheduled scan")
                    .color(TEXT)
                    .size(16.0)
                    .strong(),
            );
            ui.label(
                RichText::new(
                    "Runs a quick scan automatically at the chosen cadence via the agent service.",
                )
                .color(DIM)
                .size(11.0),
            );
            ui.add_space(6.0);
            ui.horizontal(|ui| {
                for s in [Schedule::Off, Schedule::Daily, Schedule::Weekly] {
                    if ui
                        .selectable_value(&mut self.config.schedule, s, s.label())
                        .changed()
                    {
                        dirty = true;
                    }
                }
            });
        });

        ui.add_space(8.0);
        ui.label(
            RichText::new("Settings are saved automatically and apply to your next scan.")
                .color(DIM)
                .size(11.0),
        );

        if dirty {
            self.config.save();
        }
    }

    fn about(&mut self, ui: &mut egui::Ui) {
        heading(ui, "About");
        let hero = self.hero_tex.clone();
        card(ui, CARD, |ui| {
            ui.horizontal(|ui| {
                if let Some(tex) = &hero {
                    ui.add(egui::Image::new(egui::load::SizedTexture::new(
                        tex.id(),
                        egui::vec2(128.0, 128.0),
                    )));
                    ui.add_space(14.0);
                }
                ui.vertical(|ui| {
                    ui.label(
                        RichText::new("Talos EPP — Endpoint Protection Platform")
                            .color(TEXT)
                            .size(16.0)
                            .strong(),
                    );
                    ui.label(RichText::new(format!("Version {}", self.version)).color(DIM));
                    ui.add_space(4.0);
                    ui.label(
                        RichText::new(
                            "Named for Talos — the giant bronze automaton of Greek myth that \
                             circled Crete three times a day to guard it from invaders.",
                        )
                        .color(AMBER)
                        .size(12.0)
                        .italics(),
                    );
                });
            });
            ui.add_space(10.0);
            ui.label(RichText::new("Detection layers").color(TEXT).strong());
            ui.label(RichText::new("• Hash signatures (SHA-256)").color(DIM));
            ui.label(
                RichText::new("• YARA rules (web shells, malicious PowerShell, …)").color(DIM),
            );
            ui.label(
                RichText::new("• Static PE heuristics (packing, injection imports, W^X)")
                    .color(DIM),
            );
            ui.label(
                RichText::new("• Behavioral capability analysis (CAPA-style, MITRE ATT&CK)")
                    .color(DIM),
            );
            ui.label(RichText::new("• ZIP archive inspection (zip-bomb-guarded)").color(DIM));
            ui.label(
                RichText::new("• Real-time on-access protection (scan + auto-quarantine; fanotify blocking on Linux)")
                    .color(DIM),
            );
            ui.label(
                RichText::new("• Threat-intel hash lookup (MalwareBazaar / VirusTotal)").color(DIM),
            );
            ui.add_space(8.0);
            ui.label(
                RichText::new(
                    "Signature feeds: abuse.ch (CC0) + open YARA (DRL) + optional ClamAV (GPL). \
                     See THIRD-PARTY-NOTICES.md. Real-time kernel sensor, ML and cloud are on the \
                     roadmap.",
                )
                .color(DIM),
            );
        });
    }
}

// ---- small widgets / helpers --------------------------------------------

fn nav(ui: &mut egui::Ui, current: &mut View, target: View, label: &str) {
    let selected = *current == target;
    let resp = ui.add_sized(
        [ui.available_width(), 34.0],
        egui::SelectableLabel::new(selected, RichText::new(label).size(15.0)),
    );
    if resp.clicked() {
        *current = target;
    }
}

fn nav_section(ui: &mut egui::Ui, text: &str) {
    ui.label(RichText::new(text).color(DIM).size(10.5).strong());
    ui.add_space(2.0);
}

fn heading(ui: &mut egui::Ui, text: &str) {
    ui.label(RichText::new(text).color(TEXT).size(26.0).strong());
    ui.add_space(12.0);
}

fn card<R>(ui: &mut egui::Ui, fill: Color32, add: impl FnOnce(&mut egui::Ui) -> R) -> R {
    egui::Frame::none()
        .fill(fill)
        .rounding(0.0) // Sharp enterprise edges
        .inner_margin(24.0)
        .stroke(egui::Stroke::new(1.0, Color32::from_white_alpha(15)))
        .show(ui, add)
        .inner
}

/// A metric tile that fills its column to a uniform size, so a row of them
/// reads as an aligned grid rather than a scatter of differently-sized boxes.
fn stat_tile(ui: &mut egui::Ui, title: &str, value: &str, value_col: Color32, unit: &str) {
    egui::Frame::none()
        .fill(CARD)
        .rounding(0.0)
        .inner_margin(18.0)
        .stroke(egui::Stroke::new(1.0, Color32::from_white_alpha(15)))
        .show(ui, |ui| {
            ui.set_min_width(ui.available_width());
            ui.set_min_height(80.0);
            ui.vertical(|ui| {
                ui.label(
                    RichText::new(title.to_uppercase())
                        .color(DIM)
                        .size(10.0)
                        .strong()
                        .extra_letter_spacing(1.5),
                );
                ui.add_space(8.0);
                ui.label(RichText::new(value).color(value_col).size(30.0).strong());
                ui.add_space(4.0);
                ui.label(
                    RichText::new(unit.to_uppercase())
                        .color(DIM)
                        .size(9.0)
                        .strong()
                        .extra_letter_spacing(1.0),
                );
            });
        });
}

#[derive(Clone, Copy)]
enum ModuleStatus {
    Active,
    Roadmap,
}

/// A protection-module row: title + description on the left, a status dot on
/// the right (Malwarebytes / Bitdefender Protection-tab style).
fn module_card(ui: &mut egui::Ui, name: &str, desc: &str, status: ModuleStatus) {
    card(ui, CARD, |ui| {
        ui.horizontal(|ui| {
            ui.vertical(|ui| {
                ui.label(RichText::new(name).color(TEXT).size(15.0).strong());
                ui.label(RichText::new(desc).color(DIM).size(12.0));
            });
            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                let (txt, col) = match status {
                    ModuleStatus::Active => ("ACTIVE", GREEN),
                    ModuleStatus::Roadmap => ("ROADMAP", DIM),
                };
                ui.label(
                    RichText::new(format!("● {txt}"))
                        .color(col)
                        .size(12.0)
                        .strong(),
                );
            });
        });
    });
    ui.add_space(8.0);
}

/// Like [`module_card`] but with a real on/off toggle; returns whether the
/// toggle changed this frame.
fn module_toggle(ui: &mut egui::Ui, name: &str, desc: &str, on: &mut bool) -> bool {
    let mut changed = false;
    card(ui, CARD, |ui| {
        ui.horizontal(|ui| {
            ui.vertical(|ui| {
                ui.label(RichText::new(name).color(TEXT).size(15.0).strong());
                ui.label(RichText::new(desc).color(DIM).size(12.0));
            });
            ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
                let label = if *on { "On" } else { "Off" };
                if ui.toggle_value(on, label).changed() {
                    changed = true;
                }
            });
        });
    });
    ui.add_space(8.0);
    changed
}

fn primary_button(ui: &mut egui::Ui, text: &str) -> egui::Response {
    ui.add_sized(
        [ui.available_width().min(220.0), 44.0],
        egui::Button::new(
            RichText::new(text.to_uppercase())
                .color(Color32::WHITE)
                .size(13.0)
                .strong()
                .extra_letter_spacing(1.5),
        )
        .fill(ACCENT)
        .rounding(0.0),
    )
}

fn secondary_button(ui: &mut egui::Ui, text: &str) -> egui::Response {
    ui.add_sized(
        [120.0, 36.0],
        egui::Button::new(
            RichText::new(text.to_uppercase())
                .color(TEXT)
                .size(11.0)
                .strong()
                .extra_letter_spacing(1.0),
        )
        .fill(CARD.linear_multiply(1.5))
        .rounding(0.0)
        .stroke(egui::Stroke::new(1.0, Color32::from_white_alpha(30))),
    )
}

fn advice_label(a: Advice) -> &'static str {
    match a {
        Advice::QuickScan => "Quick Scan",
        Advice::Update => "Update",
        Advice::Quarantine => "Review",
        Advice::Review => "Open Scan",
    }
}

fn sev_color(s: Severity) -> Color32 {
    match s {
        Severity::Low => DIM,
        Severity::Medium => AMBER,
        Severity::High => Color32::from_rgb(0xff, 0x6a, 0x3d),
        Severity::Critical => ACCENT,
    }
}

fn sev_tag(s: Severity) -> &'static str {
    match s {
        Severity::Low => "LOW ",
        Severity::Medium => "MED ",
        Severity::High => "HIGH",
        Severity::Critical => "CRIT",
    }
}

fn truncate(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        s.to_string()
    } else {
        let kept: String = s
            .chars()
            .rev()
            .take(max)
            .collect::<Vec<_>>()
            .into_iter()
            .rev()
            .collect();
        format!("…{kept}")
    }
}

fn now_unix() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

fn time_ago(then: u64) -> String {
    let secs = now_unix().saturating_sub(then);
    match secs {
        0..=59 => "just now".to_string(),
        60..=3599 => format!("{} min ago", secs / 60),
        3600..=86_399 => format!("{} h ago", secs / 3600),
        _ => format!("{} d ago", secs / 86_400),
    }
}

fn on_off(b: bool) -> &'static str {
    if b {
        "on"
    } else {
        "off"
    }
}

fn port_label(port: u16) -> &'static str {
    match port {
        1337 => "Leet backdoor",
        4444 => "Metasploit",
        4782 => "Quasar RAT",
        5552 => "njRAT",
        6606 | 7707 | 8808 => "AsyncRAT",
        6666 | 6667 => "IRC C2",
        6697 => "IRC C2 (TLS)",
        9001 => "Tor ORPort",
        9030 => "Tor DirPort",
        9050 => "Tor SOCKS",
        9051 => "Tor control",
        9150 => "Tor Browser",
        12345 => "NetBus",
        14433 => "XMRig HTTPS",
        14444 => "XMRig HTTP",
        31337 => "Back Orifice",
        _ => "",
    }
}

/// Format an uptime in seconds compactly (s / m / h / d).
fn fmt_uptime(secs: u64) -> String {
    match secs {
        0..=59 => format!("{secs}s"),
        60..=3599 => format!("{}m", secs / 60),
        3600..=86_399 => format!("{}h", secs / 3600),
        _ => format!("{}d", secs / 86_400),
    }
}
